// @generated by locale-dev from CLDR 48.2.3. Do not edit by hand;
// run `cargo run -p locale-dev` instead.

//! Locale identifiers and the parent locale table.

/// The CLDR release this data was generated from.
pub const CLDR_VERSION: &str = "48.2.3";
/// Identifiers of all locales, in the order of the [`Locale`] variants.
pub const AVAILABLE_LOCALES: [&str; 766] = [
    "aa",
    "aa-DJ",
    "aa-ER",
    "ab",
    "af",
    "af-NA",
    "agq",
    "ak",
    "am",
    "an",
    "ann",
    "apc",
    "ar",
    "ar-AE",
    "ar-BH",
    "ar-DJ",
    "ar-DZ",
    "ar-EG",
    "ar-EH",
    "ar-ER",
    "ar-IL",
    "ar-IQ",
    "ar-JO",
    "ar-KM",
    "ar-KW",
    "ar-LB",
    "ar-LY",
    "ar-MA",
    "ar-MR",
    "ar-OM",
    "ar-PS",
    "ar-QA",
    "ar-SA",
    "ar-SD",
    "ar-SO",
    "ar-SS",
    "ar-SY",
    "ar-TD",
    "ar-TN",
    "ar-YE",
    "arn",
    "as",
    "asa",
    "ast",
    "az",
    "az-Arab",
    "az-Arab-IQ",
    "az-Arab-TR",
    "az-Cyrl",
    "az-Latn",
    "ba",
    "bal",
    "bal-Arab",
    "bal-Latn",
    "bas",
    "be",
    "be-tarask",
    "bem",
    "bew",
    "bez",
    "bg",
    "bgc",
    "bgn",
    "bgn-AE",
    "bgn-AF",
    "bgn-IR",
    "bgn-OM",
    "bho",
    "blo",
    "blt",
    "bm",
    "bm-Nkoo",
    "bn",
    "bn-IN",
    "bo",
    "bo-IN",
    "bqi",
    "br",
    "brx",
    "bs",
    "bs-Cyrl",
    "bs-Latn",
    "bss",
    "bua",
    "byn",
    "ca",
    "ca-AD",
    "ca-ES-valencia",
    "ca-FR",
    "ca-IT",
    "cad",
    "cch",
    "ccp",
    "ccp-IN",
    "ce",
    "ceb",
    "cgg",
    "cho",
    "chr",
    "cic",
    "ckb",
    "ckb-IR",
    "co",
    "cop",
    "cs",
    "csw",
    "cu",
    "cv",
    "cy",
    "da",
    "da-GL",
    "dav",
    "de",
    "de-AT",
    "de-BE",
    "de-CH",
    "de-IT",
    "de-LI",
    "de-LU",
    "dje",
    "doi",
    "dsb",
    "dua",
    "dv",
    "dyo",
    "dz",
    "ebu",
    "ee",
    "ee-TG",
    "el",
    "el-CY",
    "el-polyton",
    "en",
    "en-001",
    "en-150",
    "en-AE",
    "en-AG",
    "en-AI",
    "en-AS",
    "en-AT",
    "en-AU",
    "en-BB",
    "en-BE",
    "en-BI",
    "en-BM",
    "en-BS",
    "en-BW",
    "en-BZ",
    "en-CA",
    "en-CC",
    "en-CH",
    "en-CK",
    "en-CM",
    "en-CX",
    "en-CY",
    "en-CZ",
    "en-DE",
    "en-DG",
    "en-DK",
    "en-DM",
    "en-Dsrt",
    "en-EE",
    "en-ER",
    "en-ES",
    "en-FI",
    "en-FJ",
    "en-FK",
    "en-FM",
    "en-FR",
    "en-GB",
    "en-GD",
    "en-GE",
    "en-GG",
    "en-GH",
    "en-GI",
    "en-GM",
    "en-GS",
    "en-GU",
    "en-GY",
    "en-HK",
    "en-HU",
    "en-ID",
    "en-IE",
    "en-IL",
    "en-IM",
    "en-IN",
    "en-IO",
    "en-IT",
    "en-JE",
    "en-JM",
    "en-JP",
    "en-KE",
    "en-KI",
    "en-KN",
    "en-KY",
    "en-LC",
    "en-LR",
    "en-LS",
    "en-LT",
    "en-LV",
    "en-MG",
    "en-MH",
    "en-MO",
    "en-MP",
    "en-MS",
    "en-MT",
    "en-MU",
    "en-MV",
    "en-MW",
    "en-MY",
    "en-NA",
    "en-NF",
    "en-NG",
    "en-NL",
    "en-NO",
    "en-NR",
    "en-NU",
    "en-NZ",
    "en-PG",
    "en-PH",
    "en-PK",
    "en-PL",
    "en-PN",
    "en-PR",
    "en-PT",
    "en-PW",
    "en-RO",
    "en-RW",
    "en-SB",
    "en-SC",
    "en-SD",
    "en-SE",
    "en-SG",
    "en-SH",
    "en-SI",
    "en-SK",
    "en-SL",
    "en-SS",
    "en-SX",
    "en-SZ",
    "en-Shaw",
    "en-TC",
    "en-TK",
    "en-TO",
    "en-TT",
    "en-TV",
    "en-TZ",
    "en-UA",
    "en-UG",
    "en-UM",
    "en-VC",
    "en-VG",
    "en-VI",
    "en-VU",
    "en-WS",
    "en-ZA",
    "en-ZM",
    "en-ZW",
    "eo",
    "es",
    "es-419",
    "es-AR",
    "es-BO",
    "es-BR",
    "es-BZ",
    "es-CL",
    "es-CO",
    "es-CR",
    "es-CU",
    "es-DO",
    "es-EA",
    "es-EC",
    "es-GQ",
    "es-GT",
    "es-HN",
    "es-IC",
    "es-MX",
    "es-NI",
    "es-PA",
    "es-PE",
    "es-PH",
    "es-PR",
    "es-PY",
    "es-SV",
    "es-US",
    "es-UY",
    "es-VE",
    "et",
    "eu",
    "ewo",
    "fa",
    "fa-AF",
    "ff",
    "ff-Adlm",
    "ff-Adlm-BF",
    "ff-Adlm-CM",
    "ff-Adlm-GH",
    "ff-Adlm-GM",
    "ff-Adlm-GW",
    "ff-Adlm-LR",
    "ff-Adlm-MR",
    "ff-Adlm-NE",
    "ff-Adlm-NG",
    "ff-Adlm-SL",
    "ff-Adlm-SN",
    "ff-Latn",
    "ff-Latn-BF",
    "ff-Latn-CM",
    "ff-Latn-GH",
    "ff-Latn-GM",
    "ff-Latn-GN",
    "ff-Latn-GW",
    "ff-Latn-LR",
    "ff-Latn-MR",
    "ff-Latn-NE",
    "ff-Latn-NG",
    "ff-Latn-SL",
    "fi",
    "fil",
    "fo",
    "fo-DK",
    "fr",
    "fr-BE",
    "fr-BF",
    "fr-BI",
    "fr-BJ",
    "fr-BL",
    "fr-CA",
    "fr-CD",
    "fr-CF",
    "fr-CG",
    "fr-CH",
    "fr-CI",
    "fr-CM",
    "fr-DJ",
    "fr-DZ",
    "fr-GA",
    "fr-GF",
    "fr-GN",
    "fr-GP",
    "fr-GQ",
    "fr-HT",
    "fr-KM",
    "fr-LU",
    "fr-MA",
    "fr-MC",
    "fr-MF",
    "fr-MG",
    "fr-ML",
    "fr-MQ",
    "fr-MR",
    "fr-MU",
    "fr-NC",
    "fr-NE",
    "fr-PF",
    "fr-PM",
    "fr-RE",
    "fr-RW",
    "fr-SC",
    "fr-SN",
    "fr-SY",
    "fr-TD",
    "fr-TG",
    "fr-TN",
    "fr-VU",
    "fr-WF",
    "fr-YT",
    "frr",
    "fur",
    "fy",
    "ga",
    "ga-GB",
    "gaa",
    "gd",
    "gez",
    "gez-ER",
    "gl",
    "gn",
    "gsw",
    "gsw-FR",
    "gsw-LI",
    "gu",
    "guz",
    "gv",
    "ha",
    "ha-Arab",
    "ha-Arab-SD",
    "ha-GH",
    "ha-NE",
    "haw",
    "he",
    "hi",
    "hi-Latn",
    "hnj",
    "hnj-Hmnp",
    "hr",
    "hr-BA",
    "hsb",
    "ht",
    "hu",
    "hy",
    "ia",
    "id",
    "ie",
    "ig",
    "ii",
    "io",
    "is",
    "it",
    "it-CH",
    "it-SM",
    "it-VA",
    "iu",
    "iu-Latn",
    "ja",
    "jbo",
    "jgo",
    "jmc",
    "jv",
    "ka",
    "kaa",
    "kaa-Cyrl",
    "kaa-Latn",
    "kab",
    "kaj",
    "kam",
    "kcg",
    "kde",
    "kea",
    "kek",
    "ken",
    "kgp",
    "khq",
    "ki",
    "kk",
    "kk-Arab",
    "kk-Cyrl",
    "kk-KZ",
    "kkj",
    "kl",
    "kln",
    "km",
    "kn",
    "ko",
    "ko-CN",
    "ko-KP",
    "kok",
    "kok-Deva",
    "kok-Latn",
    "kpe",
    "kpe-GN",
    "ks",
    "ks-Arab",
    "ks-Deva",
    "ksb",
    "ksf",
    "ksh",
    "ku",
    "ku-Arab",
    "ku-Arab-IR",
    "ku-Latn",
    "ku-Latn-IQ",
    "ku-Latn-SY",
    "ku-TR",
    "kw",
    "kxv",
    "kxv-Deva",
    "kxv-Latn",
    "kxv-Orya",
    "kxv-Telu",
    "ky",
    "la",
    "lag",
    "lb",
    "lg",
    "lij",
    "lkt",
    "lld",
    "lmo",
    "ln",
    "ln-AO",
    "ln-CF",
    "ln-CG",
    "lo",
    "lrc",
    "lrc-IQ",
    "lt",
    "ltg",
    "lu",
    "luo",
    "luy",
    "lv",
    "lzz",
    "mai",
    "mas",
    "mas-TZ",
    "mdf",
    "mer",
    "mfe",
    "mg",
    "mgh",
    "mgo",
    "mhn",
    "mi",
    "mic",
    "mk",
    "ml",
    "mn",
    "mn-Mong",
    "mn-Mong-MN",
    "mni",
    "mni-Beng",
    "mni-Mtei",
    "moh",
    "mr",
    "ms",
    "ms-Arab",
    "ms-Arab-BN",
    "ms-BN",
    "ms-ID",
    "ms-SG",
    "mt",
    "mua",
    "mus",
    "mww",
    "mww-Hmnp",
    "my",
    "myv",
    "mzn",
    "naq",
    "nb",
    "nb-SJ",
    "nd",
    "nds",
    "nds-NL",
    "ne",
    "ne-IN",
    "nl",
    "nl-AW",
    "nl-BE",
    "nl-BQ",
    "nl-CW",
    "nl-SR",
    "nl-SX",
    "nmg",
    "nn",
    "nnh",
    "no",
    "nqo",
    "nr",
    "nso",
    "nus",
    "nv",
    "ny",
    "nyn",
    "oc",
    "oc-ES",
    "oka",
    "oka-US",
    "om",
    "om-KE",
    "or",
    "os",
    "os-RU",
    "osa",
    "pa",
    "pa-Arab",
    "pa-Guru",
    "pap",
    "pap-AW",
    "pcm",
    "pi",
    "pi-Latn",
    "pis",
    "pl",
    "pms",
    "prg",
    "ps",
    "ps-PK",
    "pt",
    "pt-AO",
    "pt-CH",
    "pt-CV",
    "pt-GQ",
    "pt-GW",
    "pt-LU",
    "pt-MO",
    "pt-MZ",
    "pt-PT",
    "pt-ST",
    "pt-TL",
    "qu",
    "qu-BO",
    "qu-EC",
    "quc",
    "raj",
    "rhg",
    "rhg-Rohg",
    "rhg-Rohg-BD",
    "rif",
    "rm",
    "rn",
    "ro",
    "ro-MD",
    "rof",
    "ru",
    "ru-BY",
    "ru-KG",
    "ru-KZ",
    "ru-MD",
    "ru-UA",
    "rw",
    "rwk",
    "sa",
    "sah",
    "saq",
    "sat",
    "sat-Deva",
    "sat-Olck",
    "sbp",
    "sc",
    "scn",
    "sd",
    "sd-Arab",
    "sd-Deva",
    "sdh",
    "sdh-IQ",
    "se",
    "se-FI",
    "se-SE",
    "seh",
    "ses",
    "sg",
    "sgs",
    "shi",
    "shi-Latn",
    "shi-Tfng",
    "shn",
    "shn-TH",
    "si",
    "sid",
    "sk",
    "skr",
    "sl",
    "sma",
    "sma-NO",
    "smj",
    "smj-NO",
    "smn",
    "sms",
    "sn",
    "so",
    "so-DJ",
    "so-ET",
    "so-KE",
    "sq",
    "sq-MK",
    "sq-XK",
    "sr",
    "sr-Cyrl",
    "sr-Cyrl-BA",
    "sr-Cyrl-ME",
    "sr-Cyrl-XK",
    "sr-Latn",
    "sr-Latn-BA",
    "sr-Latn-ME",
    "sr-Latn-XK",
    "ss",
    "ss-SZ",
    "ssy",
    "st",
    "st-LS",
    "su",
    "su-Latn",
    "suz",
    "suz-Deva",
    "suz-Sunu",
    "sv",
    "sv-AX",
    "sv-FI",
    "sw",
    "sw-CD",
    "sw-KE",
    "sw-UG",
    "syr",
    "syr-SY",
    "szl",
    "ta",
    "ta-LK",
    "ta-MY",
    "ta-SG",
    "te",
    "teo",
    "teo-KE",
    "tg",
    "th",
    "ti",
    "ti-ER",
    "tig",
    "tk",
    "tn",
    "tn-BW",
    "to",
    "tok",
    "tpi",
    "tr",
    "tr-CY",
    "trv",
    "trw",
    "ts",
    "tt",
    "twq",
    "tyv",
    "tzm",
    "ug",
    "uk",
    "und",
    "ur",
    "ur-IN",
    "uz",
    "uz-Arab",
    "uz-Cyrl",
    "uz-Latn",
    "vai",
    "vai-Latn",
    "vai-Vaii",
    "ve",
    "vec",
    "vi",
    "vmw",
    "vo",
    "vun",
    "wa",
    "wae",
    "wal",
    "wbp",
    "wo",
    "xh",
    "xnr",
    "xog",
    "yav",
    "yi",
    "yo",
    "yo-BJ",
    "yrl",
    "yrl-CO",
    "yrl-VE",
    "yue",
    "yue-Hans",
    "yue-Hant",
    "yue-Hant-CN",
    "yue-Hant-MO",
    "za",
    "zgh",
    "zh",
    "zh-Hans",
    "zh-Hans-HK",
    "zh-Hans-MO",
    "zh-Hans-MY",
    "zh-Hans-SG",
    "zh-Hant",
    "zh-Hant-HK",
    "zh-Hant-MO",
    "zh-Hant-MY",
    "zh-Latn",
    "zu",
];
///A CLDR locale. There is one variant per locale of CLDR 48.2.3; variant names are the identifiers with `-` replaced by `_`.
#[cfg_attr(feature = "strum", derive(strum_macros::EnumIter))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
#[allow(non_camel_case_types)]
pub enum Locale {
    ///`aa`
    aa,
    ///`aa-DJ`
    aa_DJ,
    ///`aa-ER`
    aa_ER,
    ///`ab`
    ab,
    ///`af`
    af,
    ///`af-NA`
    af_NA,
    ///`agq`
    agq,
    ///`ak`
    ak,
    ///`am`
    am,
    ///`an`
    an,
    ///`ann`
    ann,
    ///`apc`
    apc,
    ///`ar`
    ar,
    ///`ar-AE`
    ar_AE,
    ///`ar-BH`
    ar_BH,
    ///`ar-DJ`
    ar_DJ,
    ///`ar-DZ`
    ar_DZ,
    ///`ar-EG`
    ar_EG,
    ///`ar-EH`
    ar_EH,
    ///`ar-ER`
    ar_ER,
    ///`ar-IL`
    ar_IL,
    ///`ar-IQ`
    ar_IQ,
    ///`ar-JO`
    ar_JO,
    ///`ar-KM`
    ar_KM,
    ///`ar-KW`
    ar_KW,
    ///`ar-LB`
    ar_LB,
    ///`ar-LY`
    ar_LY,
    ///`ar-MA`
    ar_MA,
    ///`ar-MR`
    ar_MR,
    ///`ar-OM`
    ar_OM,
    ///`ar-PS`
    ar_PS,
    ///`ar-QA`
    ar_QA,
    ///`ar-SA`
    ar_SA,
    ///`ar-SD`
    ar_SD,
    ///`ar-SO`
    ar_SO,
    ///`ar-SS`
    ar_SS,
    ///`ar-SY`
    ar_SY,
    ///`ar-TD`
    ar_TD,
    ///`ar-TN`
    ar_TN,
    ///`ar-YE`
    ar_YE,
    ///`arn`
    arn,
    ///`as`
    as_,
    ///`asa`
    asa,
    ///`ast`
    ast,
    ///`az`
    az,
    ///`az-Arab`
    az_Arab,
    ///`az-Arab-IQ`
    az_Arab_IQ,
    ///`az-Arab-TR`
    az_Arab_TR,
    ///`az-Cyrl`
    az_Cyrl,
    ///`az-Latn`
    az_Latn,
    ///`ba`
    ba,
    ///`bal`
    bal,
    ///`bal-Arab`
    bal_Arab,
    ///`bal-Latn`
    bal_Latn,
    ///`bas`
    bas,
    ///`be`
    be,
    ///`be-tarask`
    be_tarask,
    ///`bem`
    bem,
    ///`bew`
    bew,
    ///`bez`
    bez,
    ///`bg`
    bg,
    ///`bgc`
    bgc,
    ///`bgn`
    bgn,
    ///`bgn-AE`
    bgn_AE,
    ///`bgn-AF`
    bgn_AF,
    ///`bgn-IR`
    bgn_IR,
    ///`bgn-OM`
    bgn_OM,
    ///`bho`
    bho,
    ///`blo`
    blo,
    ///`blt`
    blt,
    ///`bm`
    bm,
    ///`bm-Nkoo`
    bm_Nkoo,
    ///`bn`
    bn,
    ///`bn-IN`
    bn_IN,
    ///`bo`
    bo,
    ///`bo-IN`
    bo_IN,
    ///`bqi`
    bqi,
    ///`br`
    br,
    ///`brx`
    brx,
    ///`bs`
    bs,
    ///`bs-Cyrl`
    bs_Cyrl,
    ///`bs-Latn`
    bs_Latn,
    ///`bss`
    bss,
    ///`bua`
    bua,
    ///`byn`
    byn,
    ///`ca`
    ca,
    ///`ca-AD`
    ca_AD,
    ///`ca-ES-valencia`
    ca_ES_valencia,
    ///`ca-FR`
    ca_FR,
    ///`ca-IT`
    ca_IT,
    ///`cad`
    cad,
    ///`cch`
    cch,
    ///`ccp`
    ccp,
    ///`ccp-IN`
    ccp_IN,
    ///`ce`
    ce,
    ///`ceb`
    ceb,
    ///`cgg`
    cgg,
    ///`cho`
    cho,
    ///`chr`
    chr,
    ///`cic`
    cic,
    ///`ckb`
    ckb,
    ///`ckb-IR`
    ckb_IR,
    ///`co`
    co,
    ///`cop`
    cop,
    ///`cs`
    cs,
    ///`csw`
    csw,
    ///`cu`
    cu,
    ///`cv`
    cv,
    ///`cy`
    cy,
    ///`da`
    da,
    ///`da-GL`
    da_GL,
    ///`dav`
    dav,
    ///`de`
    de,
    ///`de-AT`
    de_AT,
    ///`de-BE`
    de_BE,
    ///`de-CH`
    de_CH,
    ///`de-IT`
    de_IT,
    ///`de-LI`
    de_LI,
    ///`de-LU`
    de_LU,
    ///`dje`
    dje,
    ///`doi`
    doi,
    ///`dsb`
    dsb,
    ///`dua`
    dua,
    ///`dv`
    dv,
    ///`dyo`
    dyo,
    ///`dz`
    dz,
    ///`ebu`
    ebu,
    ///`ee`
    ee,
    ///`ee-TG`
    ee_TG,
    ///`el`
    el,
    ///`el-CY`
    el_CY,
    ///`el-polyton`
    el_polyton,
    ///`en`
    en,
    ///`en-001`
    en_001,
    ///`en-150`
    en_150,
    ///`en-AE`
    en_AE,
    ///`en-AG`
    en_AG,
    ///`en-AI`
    en_AI,
    ///`en-AS`
    en_AS,
    ///`en-AT`
    en_AT,
    ///`en-AU`
    en_AU,
    ///`en-BB`
    en_BB,
    ///`en-BE`
    en_BE,
    ///`en-BI`
    en_BI,
    ///`en-BM`
    en_BM,
    ///`en-BS`
    en_BS,
    ///`en-BW`
    en_BW,
    ///`en-BZ`
    en_BZ,
    ///`en-CA`
    en_CA,
    ///`en-CC`
    en_CC,
    ///`en-CH`
    en_CH,
    ///`en-CK`
    en_CK,
    ///`en-CM`
    en_CM,
    ///`en-CX`
    en_CX,
    ///`en-CY`
    en_CY,
    ///`en-CZ`
    en_CZ,
    ///`en-DE`
    en_DE,
    ///`en-DG`
    en_DG,
    ///`en-DK`
    en_DK,
    ///`en-DM`
    en_DM,
    ///`en-Dsrt`
    en_Dsrt,
    ///`en-EE`
    en_EE,
    ///`en-ER`
    en_ER,
    ///`en-ES`
    en_ES,
    ///`en-FI`
    en_FI,
    ///`en-FJ`
    en_FJ,
    ///`en-FK`
    en_FK,
    ///`en-FM`
    en_FM,
    ///`en-FR`
    en_FR,
    ///`en-GB`
    en_GB,
    ///`en-GD`
    en_GD,
    ///`en-GE`
    en_GE,
    ///`en-GG`
    en_GG,
    ///`en-GH`
    en_GH,
    ///`en-GI`
    en_GI,
    ///`en-GM`
    en_GM,
    ///`en-GS`
    en_GS,
    ///`en-GU`
    en_GU,
    ///`en-GY`
    en_GY,
    ///`en-HK`
    en_HK,
    ///`en-HU`
    en_HU,
    ///`en-ID`
    en_ID,
    ///`en-IE`
    en_IE,
    ///`en-IL`
    en_IL,
    ///`en-IM`
    en_IM,
    ///`en-IN`
    en_IN,
    ///`en-IO`
    en_IO,
    ///`en-IT`
    en_IT,
    ///`en-JE`
    en_JE,
    ///`en-JM`
    en_JM,
    ///`en-JP`
    en_JP,
    ///`en-KE`
    en_KE,
    ///`en-KI`
    en_KI,
    ///`en-KN`
    en_KN,
    ///`en-KY`
    en_KY,
    ///`en-LC`
    en_LC,
    ///`en-LR`
    en_LR,
    ///`en-LS`
    en_LS,
    ///`en-LT`
    en_LT,
    ///`en-LV`
    en_LV,
    ///`en-MG`
    en_MG,
    ///`en-MH`
    en_MH,
    ///`en-MO`
    en_MO,
    ///`en-MP`
    en_MP,
    ///`en-MS`
    en_MS,
    ///`en-MT`
    en_MT,
    ///`en-MU`
    en_MU,
    ///`en-MV`
    en_MV,
    ///`en-MW`
    en_MW,
    ///`en-MY`
    en_MY,
    ///`en-NA`
    en_NA,
    ///`en-NF`
    en_NF,
    ///`en-NG`
    en_NG,
    ///`en-NL`
    en_NL,
    ///`en-NO`
    en_NO,
    ///`en-NR`
    en_NR,
    ///`en-NU`
    en_NU,
    ///`en-NZ`
    en_NZ,
    ///`en-PG`
    en_PG,
    ///`en-PH`
    en_PH,
    ///`en-PK`
    en_PK,
    ///`en-PL`
    en_PL,
    ///`en-PN`
    en_PN,
    ///`en-PR`
    en_PR,
    ///`en-PT`
    en_PT,
    ///`en-PW`
    en_PW,
    ///`en-RO`
    en_RO,
    ///`en-RW`
    en_RW,
    ///`en-SB`
    en_SB,
    ///`en-SC`
    en_SC,
    ///`en-SD`
    en_SD,
    ///`en-SE`
    en_SE,
    ///`en-SG`
    en_SG,
    ///`en-SH`
    en_SH,
    ///`en-SI`
    en_SI,
    ///`en-SK`
    en_SK,
    ///`en-SL`
    en_SL,
    ///`en-SS`
    en_SS,
    ///`en-SX`
    en_SX,
    ///`en-SZ`
    en_SZ,
    ///`en-Shaw`
    en_Shaw,
    ///`en-TC`
    en_TC,
    ///`en-TK`
    en_TK,
    ///`en-TO`
    en_TO,
    ///`en-TT`
    en_TT,
    ///`en-TV`
    en_TV,
    ///`en-TZ`
    en_TZ,
    ///`en-UA`
    en_UA,
    ///`en-UG`
    en_UG,
    ///`en-UM`
    en_UM,
    ///`en-VC`
    en_VC,
    ///`en-VG`
    en_VG,
    ///`en-VI`
    en_VI,
    ///`en-VU`
    en_VU,
    ///`en-WS`
    en_WS,
    ///`en-ZA`
    en_ZA,
    ///`en-ZM`
    en_ZM,
    ///`en-ZW`
    en_ZW,
    ///`eo`
    eo,
    ///`es`
    es,
    ///`es-419`
    es_419,
    ///`es-AR`
    es_AR,
    ///`es-BO`
    es_BO,
    ///`es-BR`
    es_BR,
    ///`es-BZ`
    es_BZ,
    ///`es-CL`
    es_CL,
    ///`es-CO`
    es_CO,
    ///`es-CR`
    es_CR,
    ///`es-CU`
    es_CU,
    ///`es-DO`
    es_DO,
    ///`es-EA`
    es_EA,
    ///`es-EC`
    es_EC,
    ///`es-GQ`
    es_GQ,
    ///`es-GT`
    es_GT,
    ///`es-HN`
    es_HN,
    ///`es-IC`
    es_IC,
    ///`es-MX`
    es_MX,
    ///`es-NI`
    es_NI,
    ///`es-PA`
    es_PA,
    ///`es-PE`
    es_PE,
    ///`es-PH`
    es_PH,
    ///`es-PR`
    es_PR,
    ///`es-PY`
    es_PY,
    ///`es-SV`
    es_SV,
    ///`es-US`
    es_US,
    ///`es-UY`
    es_UY,
    ///`es-VE`
    es_VE,
    ///`et`
    et,
    ///`eu`
    eu,
    ///`ewo`
    ewo,
    ///`fa`
    fa,
    ///`fa-AF`
    fa_AF,
    ///`ff`
    ff,
    ///`ff-Adlm`
    ff_Adlm,
    ///`ff-Adlm-BF`
    ff_Adlm_BF,
    ///`ff-Adlm-CM`
    ff_Adlm_CM,
    ///`ff-Adlm-GH`
    ff_Adlm_GH,
    ///`ff-Adlm-GM`
    ff_Adlm_GM,
    ///`ff-Adlm-GW`
    ff_Adlm_GW,
    ///`ff-Adlm-LR`
    ff_Adlm_LR,
    ///`ff-Adlm-MR`
    ff_Adlm_MR,
    ///`ff-Adlm-NE`
    ff_Adlm_NE,
    ///`ff-Adlm-NG`
    ff_Adlm_NG,
    ///`ff-Adlm-SL`
    ff_Adlm_SL,
    ///`ff-Adlm-SN`
    ff_Adlm_SN,
    ///`ff-Latn`
    ff_Latn,
    ///`ff-Latn-BF`
    ff_Latn_BF,
    ///`ff-Latn-CM`
    ff_Latn_CM,
    ///`ff-Latn-GH`
    ff_Latn_GH,
    ///`ff-Latn-GM`
    ff_Latn_GM,
    ///`ff-Latn-GN`
    ff_Latn_GN,
    ///`ff-Latn-GW`
    ff_Latn_GW,
    ///`ff-Latn-LR`
    ff_Latn_LR,
    ///`ff-Latn-MR`
    ff_Latn_MR,
    ///`ff-Latn-NE`
    ff_Latn_NE,
    ///`ff-Latn-NG`
    ff_Latn_NG,
    ///`ff-Latn-SL`
    ff_Latn_SL,
    ///`fi`
    fi,
    ///`fil`
    fil,
    ///`fo`
    fo,
    ///`fo-DK`
    fo_DK,
    ///`fr`
    fr,
    ///`fr-BE`
    fr_BE,
    ///`fr-BF`
    fr_BF,
    ///`fr-BI`
    fr_BI,
    ///`fr-BJ`
    fr_BJ,
    ///`fr-BL`
    fr_BL,
    ///`fr-CA`
    fr_CA,
    ///`fr-CD`
    fr_CD,
    ///`fr-CF`
    fr_CF,
    ///`fr-CG`
    fr_CG,
    ///`fr-CH`
    fr_CH,
    ///`fr-CI`
    fr_CI,
    ///`fr-CM`
    fr_CM,
    ///`fr-DJ`
    fr_DJ,
    ///`fr-DZ`
    fr_DZ,
    ///`fr-GA`
    fr_GA,
    ///`fr-GF`
    fr_GF,
    ///`fr-GN`
    fr_GN,
    ///`fr-GP`
    fr_GP,
    ///`fr-GQ`
    fr_GQ,
    ///`fr-HT`
    fr_HT,
    ///`fr-KM`
    fr_KM,
    ///`fr-LU`
    fr_LU,
    ///`fr-MA`
    fr_MA,
    ///`fr-MC`
    fr_MC,
    ///`fr-MF`
    fr_MF,
    ///`fr-MG`
    fr_MG,
    ///`fr-ML`
    fr_ML,
    ///`fr-MQ`
    fr_MQ,
    ///`fr-MR`
    fr_MR,
    ///`fr-MU`
    fr_MU,
    ///`fr-NC`
    fr_NC,
    ///`fr-NE`
    fr_NE,
    ///`fr-PF`
    fr_PF,
    ///`fr-PM`
    fr_PM,
    ///`fr-RE`
    fr_RE,
    ///`fr-RW`
    fr_RW,
    ///`fr-SC`
    fr_SC,
    ///`fr-SN`
    fr_SN,
    ///`fr-SY`
    fr_SY,
    ///`fr-TD`
    fr_TD,
    ///`fr-TG`
    fr_TG,
    ///`fr-TN`
    fr_TN,
    ///`fr-VU`
    fr_VU,
    ///`fr-WF`
    fr_WF,
    ///`fr-YT`
    fr_YT,
    ///`frr`
    frr,
    ///`fur`
    fur,
    ///`fy`
    fy,
    ///`ga`
    ga,
    ///`ga-GB`
    ga_GB,
    ///`gaa`
    gaa,
    ///`gd`
    gd,
    ///`gez`
    gez,
    ///`gez-ER`
    gez_ER,
    ///`gl`
    gl,
    ///`gn`
    gn,
    ///`gsw`
    gsw,
    ///`gsw-FR`
    gsw_FR,
    ///`gsw-LI`
    gsw_LI,
    ///`gu`
    gu,
    ///`guz`
    guz,
    ///`gv`
    gv,
    ///`ha`
    ha,
    ///`ha-Arab`
    ha_Arab,
    ///`ha-Arab-SD`
    ha_Arab_SD,
    ///`ha-GH`
    ha_GH,
    ///`ha-NE`
    ha_NE,
    ///`haw`
    haw,
    ///`he`
    he,
    ///`hi`
    hi,
    ///`hi-Latn`
    hi_Latn,
    ///`hnj`
    hnj,
    ///`hnj-Hmnp`
    hnj_Hmnp,
    ///`hr`
    hr,
    ///`hr-BA`
    hr_BA,
    ///`hsb`
    hsb,
    ///`ht`
    ht,
    ///`hu`
    hu,
    ///`hy`
    hy,
    ///`ia`
    ia,
    ///`id`
    id,
    ///`ie`
    ie,
    ///`ig`
    ig,
    ///`ii`
    ii,
    ///`io`
    io,
    ///`is`
    is,
    ///`it`
    it,
    ///`it-CH`
    it_CH,
    ///`it-SM`
    it_SM,
    ///`it-VA`
    it_VA,
    ///`iu`
    iu,
    ///`iu-Latn`
    iu_Latn,
    ///`ja`
    ja,
    ///`jbo`
    jbo,
    ///`jgo`
    jgo,
    ///`jmc`
    jmc,
    ///`jv`
    jv,
    ///`ka`
    ka,
    ///`kaa`
    kaa,
    ///`kaa-Cyrl`
    kaa_Cyrl,
    ///`kaa-Latn`
    kaa_Latn,
    ///`kab`
    kab,
    ///`kaj`
    kaj,
    ///`kam`
    kam,
    ///`kcg`
    kcg,
    ///`kde`
    kde,
    ///`kea`
    kea,
    ///`kek`
    kek,
    ///`ken`
    ken,
    ///`kgp`
    kgp,
    ///`khq`
    khq,
    ///`ki`
    ki,
    ///`kk`
    kk,
    ///`kk-Arab`
    kk_Arab,
    ///`kk-Cyrl`
    kk_Cyrl,
    ///`kk-KZ`
    kk_KZ,
    ///`kkj`
    kkj,
    ///`kl`
    kl,
    ///`kln`
    kln,
    ///`km`
    km,
    ///`kn`
    kn,
    ///`ko`
    ko,
    ///`ko-CN`
    ko_CN,
    ///`ko-KP`
    ko_KP,
    ///`kok`
    kok,
    ///`kok-Deva`
    kok_Deva,
    ///`kok-Latn`
    kok_Latn,
    ///`kpe`
    kpe,
    ///`kpe-GN`
    kpe_GN,
    ///`ks`
    ks,
    ///`ks-Arab`
    ks_Arab,
    ///`ks-Deva`
    ks_Deva,
    ///`ksb`
    ksb,
    ///`ksf`
    ksf,
    ///`ksh`
    ksh,
    ///`ku`
    ku,
    ///`ku-Arab`
    ku_Arab,
    ///`ku-Arab-IR`
    ku_Arab_IR,
    ///`ku-Latn`
    ku_Latn,
    ///`ku-Latn-IQ`
    ku_Latn_IQ,
    ///`ku-Latn-SY`
    ku_Latn_SY,
    ///`ku-TR`
    ku_TR,
    ///`kw`
    kw,
    ///`kxv`
    kxv,
    ///`kxv-Deva`
    kxv_Deva,
    ///`kxv-Latn`
    kxv_Latn,
    ///`kxv-Orya`
    kxv_Orya,
    ///`kxv-Telu`
    kxv_Telu,
    ///`ky`
    ky,
    ///`la`
    la,
    ///`lag`
    lag,
    ///`lb`
    lb,
    ///`lg`
    lg,
    ///`lij`
    lij,
    ///`lkt`
    lkt,
    ///`lld`
    lld,
    ///`lmo`
    lmo,
    ///`ln`
    ln,
    ///`ln-AO`
    ln_AO,
    ///`ln-CF`
    ln_CF,
    ///`ln-CG`
    ln_CG,
    ///`lo`
    lo,
    ///`lrc`
    lrc,
    ///`lrc-IQ`
    lrc_IQ,
    ///`lt`
    lt,
    ///`ltg`
    ltg,
    ///`lu`
    lu,
    ///`luo`
    luo,
    ///`luy`
    luy,
    ///`lv`
    lv,
    ///`lzz`
    lzz,
    ///`mai`
    mai,
    ///`mas`
    mas,
    ///`mas-TZ`
    mas_TZ,
    ///`mdf`
    mdf,
    ///`mer`
    mer,
    ///`mfe`
    mfe,
    ///`mg`
    mg,
    ///`mgh`
    mgh,
    ///`mgo`
    mgo,
    ///`mhn`
    mhn,
    ///`mi`
    mi,
    ///`mic`
    mic,
    ///`mk`
    mk,
    ///`ml`
    ml,
    ///`mn`
    mn,
    ///`mn-Mong`
    mn_Mong,
    ///`mn-Mong-MN`
    mn_Mong_MN,
    ///`mni`
    mni,
    ///`mni-Beng`
    mni_Beng,
    ///`mni-Mtei`
    mni_Mtei,
    ///`moh`
    moh,
    ///`mr`
    mr,
    ///`ms`
    ms,
    ///`ms-Arab`
    ms_Arab,
    ///`ms-Arab-BN`
    ms_Arab_BN,
    ///`ms-BN`
    ms_BN,
    ///`ms-ID`
    ms_ID,
    ///`ms-SG`
    ms_SG,
    ///`mt`
    mt,
    ///`mua`
    mua,
    ///`mus`
    mus,
    ///`mww`
    mww,
    ///`mww-Hmnp`
    mww_Hmnp,
    ///`my`
    my,
    ///`myv`
    myv,
    ///`mzn`
    mzn,
    ///`naq`
    naq,
    ///`nb`
    nb,
    ///`nb-SJ`
    nb_SJ,
    ///`nd`
    nd,
    ///`nds`
    nds,
    ///`nds-NL`
    nds_NL,
    ///`ne`
    ne,
    ///`ne-IN`
    ne_IN,
    ///`nl`
    nl,
    ///`nl-AW`
    nl_AW,
    ///`nl-BE`
    nl_BE,
    ///`nl-BQ`
    nl_BQ,
    ///`nl-CW`
    nl_CW,
    ///`nl-SR`
    nl_SR,
    ///`nl-SX`
    nl_SX,
    ///`nmg`
    nmg,
    ///`nn`
    nn,
    ///`nnh`
    nnh,
    ///`no`
    no,
    ///`nqo`
    nqo,
    ///`nr`
    nr,
    ///`nso`
    nso,
    ///`nus`
    nus,
    ///`nv`
    nv,
    ///`ny`
    ny,
    ///`nyn`
    nyn,
    ///`oc`
    oc,
    ///`oc-ES`
    oc_ES,
    ///`oka`
    oka,
    ///`oka-US`
    oka_US,
    ///`om`
    om,
    ///`om-KE`
    om_KE,
    ///`or`
    or,
    ///`os`
    os,
    ///`os-RU`
    os_RU,
    ///`osa`
    osa,
    ///`pa`
    pa,
    ///`pa-Arab`
    pa_Arab,
    ///`pa-Guru`
    pa_Guru,
    ///`pap`
    pap,
    ///`pap-AW`
    pap_AW,
    ///`pcm`
    pcm,
    ///`pi`
    pi,
    ///`pi-Latn`
    pi_Latn,
    ///`pis`
    pis,
    ///`pl`
    pl,
    ///`pms`
    pms,
    ///`prg`
    prg,
    ///`ps`
    ps,
    ///`ps-PK`
    ps_PK,
    ///`pt`
    pt,
    ///`pt-AO`
    pt_AO,
    ///`pt-CH`
    pt_CH,
    ///`pt-CV`
    pt_CV,
    ///`pt-GQ`
    pt_GQ,
    ///`pt-GW`
    pt_GW,
    ///`pt-LU`
    pt_LU,
    ///`pt-MO`
    pt_MO,
    ///`pt-MZ`
    pt_MZ,
    ///`pt-PT`
    pt_PT,
    ///`pt-ST`
    pt_ST,
    ///`pt-TL`
    pt_TL,
    ///`qu`
    qu,
    ///`qu-BO`
    qu_BO,
    ///`qu-EC`
    qu_EC,
    ///`quc`
    quc,
    ///`raj`
    raj,
    ///`rhg`
    rhg,
    ///`rhg-Rohg`
    rhg_Rohg,
    ///`rhg-Rohg-BD`
    rhg_Rohg_BD,
    ///`rif`
    rif,
    ///`rm`
    rm,
    ///`rn`
    rn,
    ///`ro`
    ro,
    ///`ro-MD`
    ro_MD,
    ///`rof`
    rof,
    ///`ru`
    ru,
    ///`ru-BY`
    ru_BY,
    ///`ru-KG`
    ru_KG,
    ///`ru-KZ`
    ru_KZ,
    ///`ru-MD`
    ru_MD,
    ///`ru-UA`
    ru_UA,
    ///`rw`
    rw,
    ///`rwk`
    rwk,
    ///`sa`
    sa,
    ///`sah`
    sah,
    ///`saq`
    saq,
    ///`sat`
    sat,
    ///`sat-Deva`
    sat_Deva,
    ///`sat-Olck`
    sat_Olck,
    ///`sbp`
    sbp,
    ///`sc`
    sc,
    ///`scn`
    scn,
    ///`sd`
    sd,
    ///`sd-Arab`
    sd_Arab,
    ///`sd-Deva`
    sd_Deva,
    ///`sdh`
    sdh,
    ///`sdh-IQ`
    sdh_IQ,
    ///`se`
    se,
    ///`se-FI`
    se_FI,
    ///`se-SE`
    se_SE,
    ///`seh`
    seh,
    ///`ses`
    ses,
    ///`sg`
    sg,
    ///`sgs`
    sgs,
    ///`shi`
    shi,
    ///`shi-Latn`
    shi_Latn,
    ///`shi-Tfng`
    shi_Tfng,
    ///`shn`
    shn,
    ///`shn-TH`
    shn_TH,
    ///`si`
    si,
    ///`sid`
    sid,
    ///`sk`
    sk,
    ///`skr`
    skr,
    ///`sl`
    sl,
    ///`sma`
    sma,
    ///`sma-NO`
    sma_NO,
    ///`smj`
    smj,
    ///`smj-NO`
    smj_NO,
    ///`smn`
    smn,
    ///`sms`
    sms,
    ///`sn`
    sn,
    ///`so`
    so,
    ///`so-DJ`
    so_DJ,
    ///`so-ET`
    so_ET,
    ///`so-KE`
    so_KE,
    ///`sq`
    sq,
    ///`sq-MK`
    sq_MK,
    ///`sq-XK`
    sq_XK,
    ///`sr`
    sr,
    ///`sr-Cyrl`
    sr_Cyrl,
    ///`sr-Cyrl-BA`
    sr_Cyrl_BA,
    ///`sr-Cyrl-ME`
    sr_Cyrl_ME,
    ///`sr-Cyrl-XK`
    sr_Cyrl_XK,
    ///`sr-Latn`
    sr_Latn,
    ///`sr-Latn-BA`
    sr_Latn_BA,
    ///`sr-Latn-ME`
    sr_Latn_ME,
    ///`sr-Latn-XK`
    sr_Latn_XK,
    ///`ss`
    ss,
    ///`ss-SZ`
    ss_SZ,
    ///`ssy`
    ssy,
    ///`st`
    st,
    ///`st-LS`
    st_LS,
    ///`su`
    su,
    ///`su-Latn`
    su_Latn,
    ///`suz`
    suz,
    ///`suz-Deva`
    suz_Deva,
    ///`suz-Sunu`
    suz_Sunu,
    ///`sv`
    sv,
    ///`sv-AX`
    sv_AX,
    ///`sv-FI`
    sv_FI,
    ///`sw`
    sw,
    ///`sw-CD`
    sw_CD,
    ///`sw-KE`
    sw_KE,
    ///`sw-UG`
    sw_UG,
    ///`syr`
    syr,
    ///`syr-SY`
    syr_SY,
    ///`szl`
    szl,
    ///`ta`
    ta,
    ///`ta-LK`
    ta_LK,
    ///`ta-MY`
    ta_MY,
    ///`ta-SG`
    ta_SG,
    ///`te`
    te,
    ///`teo`
    teo,
    ///`teo-KE`
    teo_KE,
    ///`tg`
    tg,
    ///`th`
    th,
    ///`ti`
    ti,
    ///`ti-ER`
    ti_ER,
    ///`tig`
    tig,
    ///`tk`
    tk,
    ///`tn`
    tn,
    ///`tn-BW`
    tn_BW,
    ///`to`
    to,
    ///`tok`
    tok,
    ///`tpi`
    tpi,
    ///`tr`
    tr,
    ///`tr-CY`
    tr_CY,
    ///`trv`
    trv,
    ///`trw`
    trw,
    ///`ts`
    ts,
    ///`tt`
    tt,
    ///`twq`
    twq,
    ///`tyv`
    tyv,
    ///`tzm`
    tzm,
    ///`ug`
    ug,
    ///`uk`
    uk,
    ///`und`
    und,
    ///`ur`
    ur,
    ///`ur-IN`
    ur_IN,
    ///`uz`
    uz,
    ///`uz-Arab`
    uz_Arab,
    ///`uz-Cyrl`
    uz_Cyrl,
    ///`uz-Latn`
    uz_Latn,
    ///`vai`
    vai,
    ///`vai-Latn`
    vai_Latn,
    ///`vai-Vaii`
    vai_Vaii,
    ///`ve`
    ve,
    ///`vec`
    vec,
    ///`vi`
    vi,
    ///`vmw`
    vmw,
    ///`vo`
    vo,
    ///`vun`
    vun,
    ///`wa`
    wa,
    ///`wae`
    wae,
    ///`wal`
    wal,
    ///`wbp`
    wbp,
    ///`wo`
    wo,
    ///`xh`
    xh,
    ///`xnr`
    xnr,
    ///`xog`
    xog,
    ///`yav`
    yav,
    ///`yi`
    yi,
    ///`yo`
    yo,
    ///`yo-BJ`
    yo_BJ,
    ///`yrl`
    yrl,
    ///`yrl-CO`
    yrl_CO,
    ///`yrl-VE`
    yrl_VE,
    ///`yue`
    yue,
    ///`yue-Hans`
    yue_Hans,
    ///`yue-Hant`
    yue_Hant,
    ///`yue-Hant-CN`
    yue_Hant_CN,
    ///`yue-Hant-MO`
    yue_Hant_MO,
    ///`za`
    za,
    ///`zgh`
    zgh,
    ///`zh`
    zh,
    ///`zh-Hans`
    zh_Hans,
    ///`zh-Hans-HK`
    zh_Hans_HK,
    ///`zh-Hans-MO`
    zh_Hans_MO,
    ///`zh-Hans-MY`
    zh_Hans_MY,
    ///`zh-Hans-SG`
    zh_Hans_SG,
    ///`zh-Hant`
    zh_Hant,
    ///`zh-Hant-HK`
    zh_Hant_HK,
    ///`zh-Hant-MO`
    zh_Hant_MO,
    ///`zh-Hant-MY`
    zh_Hant_MY,
    ///`zh-Latn`
    zh_Latn,
    ///`zu`
    zu,
}
/// Lowercase identifier to locale.
pub(crate) static LOCALE_MAP: phf::Map<&'static str, Locale> = ::phf::Map {
    key: 16287231350648472473,
    disps: &[
        (0, 3),
        (0, 10),
        (0, 5),
        (0, 29),
        (0, 1),
        (0, 4),
        (0, 7),
        (0, 7),
        (0, 49),
        (0, 2),
        (0, 1),
        (0, 13),
        (0, 0),
        (0, 41),
        (0, 4),
        (0, 1),
        (0, 13),
        (0, 26),
        (0, 21),
        (0, 1),
        (0, 48),
        (0, 0),
        (0, 101),
        (0, 1),
        (0, 0),
        (0, 0),
        (0, 6),
        (0, 5),
        (0, 0),
        (0, 15),
        (0, 10),
        (0, 30),
        (0, 36),
        (0, 22),
        (0, 6),
        (0, 8),
        (0, 0),
        (0, 3),
        (0, 0),
        (0, 5),
        (0, 13),
        (0, 28),
        (0, 3),
        (0, 37),
        (0, 10),
        (0, 4),
        (0, 0),
        (0, 3),
        (0, 0),
        (0, 25),
        (0, 6),
        (0, 28),
        (0, 46),
        (0, 16),
        (0, 13),
        (0, 0),
        (0, 1),
        (0, 4),
        (0, 28),
        (0, 0),
        (0, 109),
        (0, 33),
        (0, 6),
        (0, 17),
        (0, 0),
        (0, 54),
        (0, 33),
        (0, 12),
        (0, 0),
        (0, 4),
        (0, 11),
        (0, 10),
        (0, 33),
        (0, 6),
        (0, 1),
        (0, 11),
        (0, 34),
        (0, 10),
        (0, 81),
        (0, 14),
        (0, 5),
        (0, 0),
        (0, 37),
        (0, 4),
        (0, 28),
        (0, 2),
        (0, 2),
        (0, 8),
        (0, 0),
        (0, 1),
        (0, 6),
        (0, 65),
        (0, 86),
        (0, 0),
        (0, 0),
        (0, 20),
        (0, 1),
        (0, 0),
        (0, 29),
        (0, 0),
        (0, 0),
        (0, 23),
        (0, 12),
        (0, 13),
        (0, 52),
        (0, 10),
        (0, 4),
        (0, 98),
        (0, 131),
        (0, 9),
        (0, 6),
        (0, 62),
        (0, 3),
        (0, 20),
        (0, 90),
        (0, 67),
        (0, 2),
        (0, 4),
        (0, 0),
        (0, 184),
        (0, 34),
        (0, 9),
        (0, 4),
        (0, 0),
        (0, 3),
        (0, 86),
        (0, 55),
        (0, 8),
        (0, 40),
        (0, 28),
        (0, 3),
        (0, 3),
        (0, 42),
        (0, 2),
        (0, 2),
        (0, 203),
        (0, 9),
        (0, 174),
        (0, 0),
        (0, 5),
        (0, 23),
        (0, 227),
        (0, 397),
        (0, 11),
        (0, 7),
        (0, 16),
        (0, 54),
        (0, 1),
        (0, 109),
        (0, 0),
        (0, 14),
        (0, 4),
        (0, 41),
        (0, 0),
        (0, 5),
        (0, 12),
        (0, 107),
        (0, 308),
        (0, 28),
        (0, 33),
        (0, 50),
        (0, 0),
        (0, 0),
        (0, 2),
        (0, 501),
        (0, 10),
        (0, 0),
        (0, 19),
        (0, 0),
        (0, 42),
        (0, 16),
        (0, 73),
        (0, 1),
        (0, 409),
        (0, 476),
        (0, 46),
        (0, 292),
        (0, 39),
        (0, 285),
        (0, 2),
        (0, 67),
        (0, 76),
        (0, 46),
        (0, 74),
        (0, 3),
        (0, 537),
        (0, 583),
        (0, 51),
        (0, 14),
        (0, 0),
        (0, 15),
        (0, 6),
        (0, 227),
        (0, 26),
        (0, 128),
        (0, 111),
        (0, 12),
        (0, 437),
        (0, 177),
        (0, 423),
        (0, 165),
        (0, 0),
        (0, 1),
        (0, 41),
        (0, 13),
        (0, 5),
        (0, 0),
        (0, 151),
        (0, 410),
        (0, 0),
        (0, 182),
        (0, 11),
        (0, 46),
        (0, 337),
        (0, 0),
        (0, 3),
        (0, 21),
        (0, 171),
        (0, 123),
        (0, 104),
        (0, 0),
        (0, 567),
        (1, 254),
        (0, 75),
        (0, 20),
        (0, 24),
        (0, 8),
        (0, 29),
        (0, 225),
        (0, 397),
        (0, 80),
        (0, 30),
        (0, 437),
        (0, 3),
        (0, 59),
        (0, 0),
        (0, 8),
        (0, 26),
        (0, 212),
        (0, 139),
        (0, 0),
        (0, 47),
        (0, 6),
        (0, 91),
        (0, 254),
        (0, 66),
        (0, 16),
        (0, 48),
        (0, 8),
        (0, 17),
        (0, 30),
        (0, 68),
        (0, 5),
        (0, 3),
        (0, 65),
        (0, 3),
    ],
    entries: &[
        ("jgo", Locale::jgo),
        ("en-tt", Locale::en_TT),
        ("sma", Locale::sma),
        ("sn", Locale::sn),
        ("fr-ml", Locale::fr_ML),
        ("sl", Locale::sl),
        ("hr-ba", Locale::hr_BA),
        ("es-pa", Locale::es_PA),
        ("ff-latn-ne", Locale::ff_Latn_NE),
        ("ff-adlm-lr", Locale::ff_Adlm_LR),
        ("sw", Locale::sw),
        ("ff-latn-ng", Locale::ff_Latn_NG),
        ("rhg-rohg-bd", Locale::rhg_Rohg_BD),
        ("fa", Locale::fa),
        ("os", Locale::os),
        ("syr", Locale::syr),
        ("hu", Locale::hu),
        ("en-nr", Locale::en_NR),
        ("en-sg", Locale::en_SG),
        ("ff-latn-gm", Locale::ff_Latn_GM),
        ("saq", Locale::saq),
        ("pa-guru", Locale::pa_Guru),
        ("bgn-om", Locale::bgn_OM),
        ("en-na", Locale::en_NA),
        ("lld", Locale::lld),
        ("syr-sy", Locale::syr_SY),
        ("kaa", Locale::kaa),
        ("ca-fr", Locale::ca_FR),
        ("ru-md", Locale::ru_MD),
        ("sd", Locale::sd),
        ("pt-st", Locale::pt_ST),
        ("fr-gp", Locale::fr_GP),
        ("fr-ga", Locale::fr_GA),
        ("fur", Locale::fur),
        ("so-et", Locale::so_ET),
        ("en-fk", Locale::en_FK),
        ("ks-arab", Locale::ks_Arab),
        ("nnh", Locale::nnh),
        ("en-nf", Locale::en_NF),
        ("luo", Locale::luo),
        ("ff-adlm", Locale::ff_Adlm),
        ("fr-gn", Locale::fr_GN),
        ("sid", Locale::sid),
        ("de-be", Locale::de_BE),
        ("fr-cf", Locale::fr_CF),
        ("sms", Locale::sms),
        ("sr-latn-me", Locale::sr_Latn_ME),
        ("chr", Locale::chr),
        ("mr", Locale::mr),
        ("fr-mg", Locale::fr_MG),
        ("aa-dj", Locale::aa_DJ),
        ("fr-gq", Locale::fr_GQ),
        ("en-jm", Locale::en_JM),
        ("ar-qa", Locale::ar_QA),
        ("mgo", Locale::mgo),
        ("rw", Locale::rw),
        ("kaj", Locale::kaj),
        ("nb-sj", Locale::nb_SJ),
        ("en-pl", Locale::en_PL),
        ("en", Locale::en),
        ("ff-latn-gw", Locale::ff_Latn_GW),
        ("fr-yt", Locale::fr_YT),
        ("prg", Locale::prg),
        ("kn", Locale::kn),
        ("en-pt", Locale::en_PT),
        ("mww-hmnp", Locale::mww_Hmnp),
        ("zh", Locale::zh),
        ("lo", Locale::lo),
        ("ru-by", Locale::ru_BY),
        ("nl-be", Locale::nl_BE),
        ("bal-arab", Locale::bal_Arab),
        ("qu-ec", Locale::qu_EC),
        ("kxv-deva", Locale::kxv_Deva),
        ("pa", Locale::pa),
        ("sg", Locale::sg),
        ("ceb", Locale::ceb),
        ("ar-om", Locale::ar_OM),
        ("it-va", Locale::it_VA),
        ("suz", Locale::suz),
        ("seh", Locale::seh),
        ("wa", Locale::wa),
        ("ve", Locale::ve),
        ("om-ke", Locale::om_KE),
        ("en-de", Locale::en_DE),
        ("ar-sy", Locale::ar_SY),
        ("ku-tr", Locale::ku_TR),
        ("bgn", Locale::bgn),
        ("lv", Locale::lv),
        ("es-bo", Locale::es_BO),
        ("vo", Locale::vo),
        ("de-li", Locale::de_LI),
        ("ln-ao", Locale::ln_AO),
        ("cho", Locale::cho),
        ("kl", Locale::kl),
        ("az-arab", Locale::az_Arab),
        ("sd-arab", Locale::sd_Arab),
        ("agq", Locale::agq),
        ("el-cy", Locale::el_CY),
        ("en-ke", Locale::en_KE),
        ("oka-us", Locale::oka_US),
        ("mhn", Locale::mhn),
        ("cop", Locale::cop),
        ("en-sl", Locale::en_SL),
        ("kxv", Locale::kxv),
        ("kxv-telu", Locale::kxv_Telu),
        ("en-gh", Locale::en_GH),
        ("en-ae", Locale::en_AE),
        ("en-bs", Locale::en_BS),
        ("se-fi", Locale::se_FI),
        ("trv", Locale::trv),
        ("mgh", Locale::mgh),
        ("en-dg", Locale::en_DG),
        ("mus", Locale::mus),
        ("az-arab-iq", Locale::az_Arab_IQ),
        ("en-zw", Locale::en_ZW),
        ("qu-bo", Locale::qu_BO),
        ("qu", Locale::qu),
        ("ak", Locale::ak),
        ("mni-beng", Locale::mni_Beng),
        ("vai-latn", Locale::vai_Latn),
        ("bs-latn", Locale::bs_Latn),
        ("bgn-af", Locale::bgn_AF),
        ("ff-latn-lr", Locale::ff_Latn_LR),
        ("bem", Locale::bem),
        ("yo", Locale::yo),
        ("ff-adlm-bf", Locale::ff_Adlm_BF),
        ("bho", Locale::bho),
        ("ckb", Locale::ckb),
        ("nl-sx", Locale::nl_SX),
        ("en-sz", Locale::en_SZ),
        ("sr", Locale::sr),
        ("en-ck", Locale::en_CK),
        ("so-ke", Locale::so_KE),
        ("zh-hant-mo", Locale::zh_Hant_MO),
        ("ur", Locale::ur),
        ("en-tv", Locale::en_TV),
        ("fr-sc", Locale::fr_SC),
        ("en-gb", Locale::en_GB),
        ("pt-gq", Locale::pt_GQ),
        ("fr-td", Locale::fr_TD),
        ("es-co", Locale::es_CO),
        ("en-as", Locale::en_AS),
        ("ks", Locale::ks),
        ("fi", Locale::fi),
        ("yue-hant", Locale::yue_Hant),
        ("fr-bf", Locale::fr_BF),
        ("sw-cd", Locale::sw_CD),
        ("an", Locale::an),
        ("rhg", Locale::rhg),
        ("en-zm", Locale::en_ZM),
        ("kde", Locale::kde),
        ("ksh", Locale::ksh),
        ("yo-bj", Locale::yo_BJ),
        ("rof", Locale::rof),
        ("xnr", Locale::xnr),
        ("vai", Locale::vai),
        ("be", Locale::be),
        ("ln", Locale::ln),
        ("cad", Locale::cad),
        ("pap", Locale::pap),
        ("ff-adlm-gm", Locale::ff_Adlm_GM),
        ("szl", Locale::szl),
        ("fr-bi", Locale::fr_BI),
        ("es", Locale::es),
        ("en-kn", Locale::en_KN),
        ("en-cc", Locale::en_CC),
        ("en-bi", Locale::en_BI),
        ("zh-hans-my", Locale::zh_Hans_MY),
        ("kpe", Locale::kpe),
        ("en-ge", Locale::en_GE),
        ("ken", Locale::ken),
        ("es-mx", Locale::es_MX),
        ("nl-aw", Locale::nl_AW),
        ("ff-adlm-ng", Locale::ff_Adlm_NG),
        ("en-nz", Locale::en_NZ),
        ("br", Locale::br),
        ("ms-id", Locale::ms_ID),
        ("fo", Locale::fo),
        ("en-ag", Locale::en_AG),
        ("oc-es", Locale::oc_ES),
        ("fr-tg", Locale::fr_TG),
        ("tr", Locale::tr),
        ("byn", Locale::byn),
        ("sr-latn-xk", Locale::sr_Latn_XK),
        ("ss-sz", Locale::ss_SZ),
        ("kxv-latn", Locale::kxv_Latn),
        ("nv", Locale::nv),
        ("es-us", Locale::es_US),
        ("ltg", Locale::ltg),
        ("mas-tz", Locale::mas_TZ),
        ("ar-ma", Locale::ar_MA),
        ("kk-arab", Locale::kk_Arab),
        ("sah", Locale::sah),
        ("en-in", Locale::en_IN),
        ("twq", Locale::twq),
        ("ar-eg", Locale::ar_EG),
        ("zu", Locale::zu),
        ("ff-latn-mr", Locale::ff_Latn_MR),
        ("ps", Locale::ps),
        ("bgn-ae", Locale::bgn_AE),
        ("ff-latn-sl", Locale::ff_Latn_SL),
        ("yrl-co", Locale::yrl_CO),
        ("en-fr", Locale::en_FR),
        ("blt", Locale::blt),
        ("raj", Locale::raj),
        ("es-py", Locale::es_PY),
        ("ku", Locale::ku),
        ("en-za", Locale::en_ZA),
        ("ta-sg", Locale::ta_SG),
        ("brx", Locale::brx),
        ("zh-hans-hk", Locale::zh_Hans_HK),
        ("kcg", Locale::kcg),
        ("en-cm", Locale::en_CM),
        ("mg", Locale::mg),
        ("ku-arab", Locale::ku_Arab),
        ("xog", Locale::xog),
        ("ha", Locale::ha),
        ("guz", Locale::guz),
        ("ses", Locale::ses),
        ("fr-mr", Locale::fr_MR),
        ("fr-re", Locale::fr_RE),
        ("rn", Locale::rn),
        ("az-latn", Locale::az_Latn),
        ("oc", Locale::oc),
        ("ks-deva", Locale::ks_Deva),
        ("ps-pk", Locale::ps_PK),
        ("skr", Locale::skr),
        ("ku-latn", Locale::ku_Latn),
        ("es-cu", Locale::es_CU),
        ("sma-no", Locale::sma_NO),
        ("su-latn", Locale::su_Latn),
        ("en-cx", Locale::en_CX),
        ("sbp", Locale::sbp),
        ("fr-ci", Locale::fr_CI),
        ("ee-tg", Locale::ee_TG),
        ("bn-in", Locale::bn_IN),
        ("ss", Locale::ss),
        ("blo", Locale::blo),
        ("kw", Locale::kw),
        ("en-bw", Locale::en_BW),
        ("en-ie", Locale::en_IE),
        ("ksf", Locale::ksf),
        ("kok", Locale::kok),
        ("khq", Locale::khq),
        ("shi-latn", Locale::shi_Latn),
        ("ebu", Locale::ebu),
        ("es-ar", Locale::es_AR),
        ("ff-latn-gh", Locale::ff_Latn_GH),
        ("ne-in", Locale::ne_IN),
        ("kxv-orya", Locale::kxv_Orya),
        ("fr-pf", Locale::fr_PF),
        ("fr-sy", Locale::fr_SY),
        ("nl-cw", Locale::nl_CW),
        ("jv", Locale::jv),
        ("sr-latn", Locale::sr_Latn),
        ("naq", Locale::naq),
        ("sr-cyrl", Locale::sr_Cyrl),
        ("en-ph", Locale::en_PH),
        ("kaa-latn", Locale::kaa_Latn),
        ("si", Locale::si),
        ("en-ee", Locale::en_EE),
        ("frr", Locale::frr),
        ("kok-latn", Locale::kok_Latn),
        ("en-150", Locale::en_150),
        ("ii", Locale::ii),
        ("ku-latn-sy", Locale::ku_Latn_SY),
        ("en-mo", Locale::en_MO),
        ("ca-ad", Locale::ca_AD),
        ("ky", Locale::ky),
        ("el", Locale::el),
        ("es-cr", Locale::es_CR),
        ("ff-latn-cm", Locale::ff_Latn_CM),
        ("ar-ps", Locale::ar_PS),
        ("kam", Locale::kam),
        ("en-ky", Locale::en_KY),
        ("sk", Locale::sk),
        ("ro", Locale::ro),
        ("cu", Locale::cu),
        ("ku-latn-iq", Locale::ku_Latn_IQ),
        ("shi-tfng", Locale::shi_Tfng),
        ("ms-sg", Locale::ms_SG),
        ("en-gs", Locale::en_GS),
        ("en-nu", Locale::en_NU),
        ("en-vg", Locale::en_VG),
        ("en-se", Locale::en_SE),
        ("teo-ke", Locale::teo_KE),
        ("bqi", Locale::bqi),
        ("fr-ma", Locale::fr_MA),
        ("mww", Locale::mww),
        ("ml", Locale::ml),
        ("fr-pm", Locale::fr_PM),
        ("sq-xk", Locale::sq_XK),
        ("bo-in", Locale::bo_IN),
        ("en-pk", Locale::en_PK),
        ("it-sm", Locale::it_SM),
        ("la", Locale::la),
        ("vi", Locale::vi),
        ("yue", Locale::yue),
        ("sr-cyrl-xk", Locale::sr_Cyrl_XK),
        ("oka", Locale::oka),
        ("en-gu", Locale::en_GU),
        ("nr", Locale::nr),
        ("en-fm", Locale::en_FM),
        ("en-sb", Locale::en_SB),
        ("sdh", Locale::sdh),
        ("bs", Locale::bs),
        ("en-ws", Locale::en_WS),
        ("pt-tl", Locale::pt_TL),
        ("fil", Locale::fil),
        ("ar-iq", Locale::ar_IQ),
        ("fr-sn", Locale::fr_SN),
        ("pt-mo", Locale::pt_MO),
        ("he", Locale::he),
        ("lb", Locale::lb),
        ("ssy", Locale::ssy),
        ("apc", Locale::apc),
        ("en-hu", Locale::en_HU),
        ("en-shaw", Locale::en_Shaw),
        ("tig", Locale::tig),
        ("vun", Locale::vun),
        ("gl", Locale::gl),
        ("sat-olck", Locale::sat_Olck),
        ("mfe", Locale::mfe),
        ("arn", Locale::arn),
        ("es-ph", Locale::es_PH),
        ("de-at", Locale::de_AT),
        ("ksb", Locale::ksb),
        ("es-bz", Locale::es_BZ),
        ("ms", Locale::ms),
        ("za", Locale::za),
        ("ti-er", Locale::ti_ER),
        ("fr-dj", Locale::fr_DJ),
        ("gsw", Locale::gsw),
        ("sw-ug", Locale::sw_UG),
        ("hnj-hmnp", Locale::hnj_Hmnp),
        ("ff-adlm-sl", Locale::ff_Adlm_SL),
        ("pl", Locale::pl),
        ("en-bz", Locale::en_BZ),
        ("en-mw", Locale::en_MW),
        ("it", Locale::it),
        ("tpi", Locale::tpi),
        ("bn", Locale::bn),
        ("ug", Locale::ug),
        ("lu", Locale::lu),
        ("en-cy", Locale::en_CY),
        ("ru-ua", Locale::ru_UA),
        ("or", Locale::or),
        ("fa-af", Locale::fa_AF),
        ("ann", Locale::ann),
        ("vai-vaii", Locale::vai_Vaii),
        ("sdh-iq", Locale::sdh_IQ),
        ("ar-ye", Locale::ar_YE),
        ("fr-vu", Locale::fr_VU),
        ("ba", Locale::ba),
        ("luy", Locale::luy),
        ("ff-latn-gn", Locale::ff_Latn_GN),
        ("en-es", Locale::en_ES),
        ("fr-rw", Locale::fr_RW),
        ("vmw", Locale::vmw),
        ("smn", Locale::smn),
        ("es-gt", Locale::es_GT),
        ("en-im", Locale::en_IM),
        ("fr-ch", Locale::fr_CH),
        ("dje", Locale::dje),
        ("nl", Locale::nl),
        ("ar-dj", Locale::ar_DJ),
        ("quc", Locale::quc),
        ("vec", Locale::vec),
        ("fr-km", Locale::fr_KM),
        ("mn", Locale::mn),
        ("lrc-iq", Locale::lrc_IQ),
        ("it-ch", Locale::it_CH),
        ("eo", Locale::eo),
        ("af", Locale::af),
        ("ar-ae", Locale::ar_AE),
        ("uz", Locale::uz),
        ("lrc", Locale::lrc),
        ("sa", Locale::sa),
        ("iu-latn", Locale::iu_Latn),
        ("cv", Locale::cv),
        ("ast", Locale::ast),
        ("ar-ss", Locale::ar_SS),
        ("kea", Locale::kea),
        ("lzz", Locale::lzz),
        ("yue-hant-cn", Locale::yue_Hant_CN),
        ("nl-bq", Locale::nl_BQ),
        ("kk", Locale::kk),
        ("bs-cyrl", Locale::bs_Cyrl),
        ("ha-arab-sd", Locale::ha_Arab_SD),
        ("sat-deva", Locale::sat_Deva),
        ("zh-hans-sg", Locale::zh_Hans_SG),
        ("en-tk", Locale::en_TK),
        ("en-mu", Locale::en_MU),
        ("mer", Locale::mer),
        ("ar-sa", Locale::ar_SA),
        ("kgp", Locale::kgp),
        ("lmo", Locale::lmo),
        ("bm-nkoo", Locale::bm_Nkoo),
        ("wo", Locale::wo),
        ("bgn-ir", Locale::bgn_IR),
        ("az-cyrl", Locale::az_Cyrl),
        ("sr-cyrl-me", Locale::sr_Cyrl_ME),
        ("es-uy", Locale::es_UY),
        ("fr-cm", Locale::fr_CM),
        ("fr-gf", Locale::fr_GF),
        ("st-ls", Locale::st_LS),
        ("en-tc", Locale::en_TC),
        ("lkt", Locale::lkt),
        ("ka", Locale::ka),
        ("tt", Locale::tt),
        ("en-bb", Locale::en_BB),
        ("mas", Locale::mas),
        ("es-pe", Locale::es_PE),
        ("ar", Locale::ar),
        ("sv-fi", Locale::sv_FI),
        ("moh", Locale::moh),
        ("ee", Locale::ee),
        ("ms-arab-bn", Locale::ms_Arab_BN),
        ("suz-deva", Locale::suz_Deva),
        ("ar-ly", Locale::ar_LY),
        ("be-tarask", Locale::be_tarask),
        ("gn", Locale::gn),
        ("eu", Locale::eu),
        ("en-ai", Locale::en_AI),
        ("cic", Locale::cic),
        ("es-ec", Locale::es_EC),
        ("ta-my", Locale::ta_MY),
        ("en-ng", Locale::en_NG),
        ("ar-bh", Locale::ar_BH),
        ("ja", Locale::ja),
        ("as", Locale::as_),
        ("ga", Locale::ga),
        ("az", Locale::az),
        ("ny", Locale::ny),
        ("mai", Locale::mai),
        ("pa-arab", Locale::pa_Arab),
        ("kln", Locale::kln),
        ("mua", Locale::mua),
        ("scn", Locale::scn),
        ("ab", Locale::ab),
        ("kk-kz", Locale::kk_KZ),
        ("ro-md", Locale::ro_MD),
        ("gu", Locale::gu),
        ("bg", Locale::bg),
        ("sd-deva", Locale::sd_Deva),
        ("ar-kw", Locale::ar_KW),
        ("en-sc", Locale::en_SC),
        ("km", Locale::km),
        ("hnj", Locale::hnj),
        ("tzm", Locale::tzm),
        ("ar-er", Locale::ar_ER),
        ("es-ni", Locale::es_NI),
        ("yrl-ve", Locale::yrl_VE),
        ("my", Locale::my),
        ("pt-pt", Locale::pt_PT),
        ("en-gm", Locale::en_GM),
        ("uz-cyrl", Locale::uz_Cyrl),
        ("en-rw", Locale::en_RW),
        ("mn-mong", Locale::mn_Mong),
        ("en-ug", Locale::en_UG),
        ("lt", Locale::lt),
        ("ar-lb", Locale::ar_LB),
        ("mzn", Locale::mzn),
        ("ha-arab", Locale::ha_Arab),
        ("pt-gw", Locale::pt_GW),
        ("tn", Locale::tn),
        ("mic", Locale::mic),
        ("ku-arab-ir", Locale::ku_Arab_IR),
        ("en-lc", Locale::en_LC),
        ("ln-cf", Locale::ln_CF),
        ("hi", Locale::hi),
        ("bew", Locale::bew),
        ("aa", Locale::aa),
        ("en-001", Locale::en_001),
        ("en-hk", Locale::en_HK),
        ("uz-latn", Locale::uz_Latn),
        ("bo", Locale::bo),
        ("gv", Locale::gv),
        ("rm", Locale::rm),
        ("gsw-li", Locale::gsw_LI),
        ("rif", Locale::rif),
        ("yue-hans", Locale::yue_Hans),
        ("en-io", Locale::en_IO),
        ("os-ru", Locale::os_RU),
        ("smj", Locale::smj),
        ("en-vi", Locale::en_VI),
        ("mk", Locale::mk),
        ("ht", Locale::ht),
        ("da", Locale::da),
        ("asa", Locale::asa),
        ("ie", Locale::ie),
        ("en-lr", Locale::en_LR),
        ("fr-mc", Locale::fr_MC),
        ("en-ls", Locale::en_LS),
        ("sr-cyrl-ba", Locale::sr_Cyrl_BA),
        ("nd", Locale::nd),
        ("en-ua", Locale::en_UA),
        ("pt-ao", Locale::pt_AO),
        ("en-sh", Locale::en_SH),
        ("ms-arab", Locale::ms_Arab),
        ("en-ms", Locale::en_MS),
        ("tk", Locale::tk),
        ("fy", Locale::fy),
        ("es-ea", Locale::es_EA),
        ("th", Locale::th),
        ("lag", Locale::lag),
        ("en-to", Locale::en_TO),
        ("hr", Locale::hr),
        ("mt", Locale::mt),
        ("es-do", Locale::es_DO),
        ("ta", Locale::ta),
        ("ff-adlm-cm", Locale::ff_Adlm_CM),
        ("en-gg", Locale::en_GG),
        ("gez-er", Locale::gez_ER),
        ("fr-mu", Locale::fr_MU),
        ("tn-bw", Locale::tn_BW),
        ("ko-cn", Locale::ko_CN),
        ("yi", Locale::yi),
        ("nso", Locale::nso),
        ("en-nl", Locale::en_NL),
        ("en-no", Locale::en_NO),
        ("fr-bj", Locale::fr_BJ),
        ("se", Locale::se),
        ("zh-hans", Locale::zh_Hans),
        ("kk-cyrl", Locale::kk_Cyrl),
        ("jmc", Locale::jmc),
        ("dav", Locale::dav),
        ("ff-adlm-sn", Locale::ff_Adlm_SN),
        ("ff-adlm-ne", Locale::ff_Adlm_NE),
        ("bss", Locale::bss),
        ("en-pn", Locale::en_PN),
        ("co", Locale::co),
        ("bal-latn", Locale::bal_Latn),
        ("en-it", Locale::en_IT),
        ("ha-gh", Locale::ha_GH),
        ("en-ca", Locale::en_CA),
        ("haw", Locale::haw),
        ("ms-bn", Locale::ms_BN),
        ("smj-no", Locale::smj_NO),
        ("sq", Locale::sq),
        ("mni", Locale::mni),
        ("ln-cg", Locale::ln_CG),
        ("en-my", Locale::en_MY),
        ("en-il", Locale::en_IL),
        ("nyn", Locale::nyn),
        ("id", Locale::id),
        ("en-jp", Locale::en_JP),
        ("trw", Locale::trw),
        ("tr-cy", Locale::tr_CY),
        ("bal", Locale::bal),
        ("cch", Locale::cch),
        ("en-dk", Locale::en_DK),
        ("en-si", Locale::en_SI),
        ("gaa", Locale::gaa),
        ("az-arab-tr", Locale::az_Arab_TR),
        ("nb", Locale::nb),
        ("hy", Locale::hy),
        ("en-er", Locale::en_ER),
        ("ko-kp", Locale::ko_KP),
        ("en-sx", Locale::en_SX),
        ("zgh", Locale::zgh),
        ("ca", Locale::ca),
        ("gsw-fr", Locale::gsw_FR),
        ("ccp-in", Locale::ccp_IN),
        ("csw", Locale::csw),
        ("fr-tn", Locale::fr_TN),
        ("bgc", Locale::bgc),
        ("ga-gb", Locale::ga_GB),
        ("sv", Locale::sv),
        ("en-mg", Locale::en_MG),
        ("en-ch", Locale::en_CH),
        ("kok-deva", Locale::kok_Deva),
        ("yav", Locale::yav),
        ("ewo", Locale::ewo),
        ("ca-es-valencia", Locale::ca_ES_valencia),
        ("am", Locale::am),
        ("nmg", Locale::nmg),
        ("nds-nl", Locale::nds_NL),
        ("en-mp", Locale::en_MP),
        ("ce", Locale::ce),
        ("es-cl", Locale::es_CL),
        ("nn", Locale::nn),
        ("pi-latn", Locale::pi_Latn),
        ("ko", Locale::ko),
        ("ar-jo", Locale::ar_JO),
        ("en-gi", Locale::en_GI),
        ("ar-tn", Locale::ar_TN),
        ("pt", Locale::pt),
        ("zh-latn", Locale::zh_Latn),
        ("sgs", Locale::sgs),
        ("fr-be", Locale::fr_BE),
        ("ts", Locale::ts),
        ("en-ss", Locale::en_SS),
        ("en-bm", Locale::en_BM),
        ("ar-dz", Locale::ar_DZ),
        ("ff", Locale::ff),
        ("fr-bl", Locale::fr_BL),
        ("mni-mtei", Locale::mni_Mtei),
        ("ru-kg", Locale::ru_KG),
        ("dsb", Locale::dsb),
        ("pis", Locale::pis),
        ("en-um", Locale::en_UM),
        ("lg", Locale::lg),
        ("no", Locale::no),
        ("bas", Locale::bas),
        ("es-br", Locale::es_BR),
        ("en-sk", Locale::en_SK),
        ("en-at", Locale::en_AT),
        ("tyv", Locale::tyv),
        ("es-hn", Locale::es_HN),
        ("lij", Locale::lij),
        ("ki", Locale::ki),
        ("fr", Locale::fr),
        ("ff-adlm-gh", Locale::ff_Adlm_GH),
        ("bez", Locale::bez),
        ("kkj", Locale::kkj),
        ("en-be", Locale::en_BE),
        ("ia", Locale::ia),
        ("nds", Locale::nds),
        ("suz-sunu", Locale::suz_Sunu),
        ("en-pw", Locale::en_PW),
        ("bua", Locale::bua),
        ("myv", Locale::myv),
        ("sc", Locale::sc),
        ("xh", Locale::xh),
        ("fr-ne", Locale::fr_NE),
        ("fr-mq", Locale::fr_MQ),
        ("es-ve", Locale::es_VE),
        ("kek", Locale::kek),
        ("en-tz", Locale::en_TZ),
        ("fr-nc", Locale::fr_NC),
        ("zh-hant-hk", Locale::zh_Hant_HK),
        ("ff-latn-bf", Locale::ff_Latn_BF),
        ("dz", Locale::dz),
        ("sr-latn-ba", Locale::sr_Latn_BA),
        ("se-se", Locale::se_SE),
        ("is", Locale::is),
        ("de", Locale::de),
        ("en-ro", Locale::en_RO),
        ("en-vu", Locale::en_VU),
        ("ti", Locale::ti),
        ("osa", Locale::osa),
        ("ff-adlm-gw", Locale::ff_Adlm_GW),
        ("iu", Locale::iu),
        ("pt-lu", Locale::pt_LU),
        ("pt-cv", Locale::pt_CV),
        ("nqo", Locale::nqo),
        ("dv", Locale::dv),
        ("jbo", Locale::jbo),
        ("da-gl", Locale::da_GL),
        ("nl-sr", Locale::nl_SR),
        ("ur-in", Locale::ur_IN),
        ("sq-mk", Locale::sq_MK),
        ("af-na", Locale::af_NA),
        ("zh-hant", Locale::zh_Hant),
        ("fr-cg", Locale::fr_CG),
        ("ru-kz", Locale::ru_KZ),
        ("dua", Locale::dua),
        ("zh-hans-mo", Locale::zh_Hans_MO),
        ("ar-eh", Locale::ar_EH),
        ("fr-mf", Locale::fr_MF),
        ("ru", Locale::ru),
        ("bm", Locale::bm),
        ("fr-ht", Locale::fr_HT),
        ("pms", Locale::pms),
        ("ar-il", Locale::ar_IL),
        ("ar-so", Locale::ar_SO),
        ("en-au", Locale::en_AU),
        ("mi", Locale::mi),
        ("pt-ch", Locale::pt_CH),
        ("te", Locale::te),
        ("pap-aw", Locale::pap_AW),
        ("und", Locale::und),
        ("en-gy", Locale::en_GY),
        ("en-pg", Locale::en_PG),
        ("en-ki", Locale::en_KI),
        ("so-dj", Locale::so_DJ),
        ("shn-th", Locale::shn_TH),
        ("ar-mr", Locale::ar_MR),
        ("io", Locale::io),
        ("es-ic", Locale::es_IC),
        ("gd", Locale::gd),
        ("rwk", Locale::rwk),
        ("dyo", Locale::dyo),
        ("so", Locale::so),
        ("ar-td", Locale::ar_TD),
        ("es-419", Locale::es_419),
        ("en-id", Locale::en_ID),
        ("cs", Locale::cs),
        ("ar-km", Locale::ar_KM),
        ("kab", Locale::kab),
        ("ckb-ir", Locale::ckb_IR),
        ("cy", Locale::cy),
        ("et", Locale::et),
        ("en-lt", Locale::en_LT),
        ("en-gd", Locale::en_GD),
        ("ca-it", Locale::ca_IT),
        ("fr-dz", Locale::fr_DZ),
        ("es-gq", Locale::es_GQ),
        ("en-je", Locale::en_JE),
        ("aa-er", Locale::aa_ER),
        ("sv-ax", Locale::sv_AX),
        ("es-sv", Locale::es_SV),
        ("ar-sd", Locale::ar_SD),
        ("fr-ca", Locale::fr_CA),
        ("fr-lu", Locale::fr_LU),
        ("ta-lk", Locale::ta_LK),
        ("fo-dk", Locale::fo_DK),
        ("mdf", Locale::mdf),
        ("cgg", Locale::cgg),
        ("kpe-gn", Locale::kpe_GN),
        ("hsb", Locale::hsb),
        ("yue-hant-mo", Locale::yue_Hant_MO),
        ("ccp", Locale::ccp),
        ("mn-mong-mn", Locale::mn_Mong_MN),
        ("en-mv", Locale::en_MV),
        ("en-mt", Locale::en_MT),
        ("de-ch", Locale::de_CH),
        ("en-pr", Locale::en_PR),
        ("zh-hant-my", Locale::zh_Hant_MY),
        ("yrl", Locale::yrl),
        ("en-fi", Locale::en_FI),
        ("ha-ne", Locale::ha_NE),
        ("es-pr", Locale::es_PR),
        ("hi-latn", Locale::hi_Latn),
        ("ne", Locale::ne),
        ("en-cz", Locale::en_CZ),
        ("el-polyton", Locale::el_polyton),
        ("gez", Locale::gez),
        ("kaa-cyrl", Locale::kaa_Cyrl),
        ("en-sd", Locale::en_SD),
        ("nus", Locale::nus),
        ("en-vc", Locale::en_VC),
        ("tok", Locale::tok),
        ("en-lv", Locale::en_LV),
        ("wal", Locale::wal),
        ("to", Locale::to),
        ("en-dsrt", Locale::en_Dsrt),
        ("ff-adlm-mr", Locale::ff_Adlm_MR),
        ("shi", Locale::shi),
        ("shn", Locale::shn),
        ("uk", Locale::uk),
        ("en-fj", Locale::en_FJ),
        ("de-lu", Locale::de_LU),
        ("wbp", Locale::wbp),
        ("teo", Locale::teo),
        ("pi", Locale::pi),
        ("en-mh", Locale::en_MH),
        ("om", Locale::om),
        ("rhg-rohg", Locale::rhg_Rohg),
        ("ff-latn", Locale::ff_Latn),
        ("ig", Locale::ig),
        ("de-it", Locale::de_IT),
        ("en-dm", Locale::en_DM),
        ("st", Locale::st),
        ("sat", Locale::sat),
        ("sw-ke", Locale::sw_KE),
        ("fr-cd", Locale::fr_CD),
        ("tg", Locale::tg),
        ("su", Locale::su),
        ("wae", Locale::wae),
        ("fr-wf", Locale::fr_WF),
        ("doi", Locale::doi),
        ("pt-mz", Locale::pt_MZ),
        ("pcm", Locale::pcm),
        ("uz-arab", Locale::uz_Arab),
    ],
};

pub(crate) static PARENTS: [Option<Locale>; 766] = [
    None,                     // aa
    Some(Locale::aa),         // aa-DJ
    Some(Locale::aa),         // aa-ER
    None,                     // ab
    None,                     // af
    Some(Locale::af),         // af-NA
    None,                     // agq
    None,                     // ak
    None,                     // am
    None,                     // an
    None,                     // ann
    None,                     // apc
    None,                     // ar
    Some(Locale::ar),         // ar-AE
    Some(Locale::ar),         // ar-BH
    Some(Locale::ar),         // ar-DJ
    Some(Locale::ar),         // ar-DZ
    Some(Locale::ar),         // ar-EG
    Some(Locale::ar),         // ar-EH
    Some(Locale::ar),         // ar-ER
    Some(Locale::ar),         // ar-IL
    Some(Locale::ar),         // ar-IQ
    Some(Locale::ar),         // ar-JO
    Some(Locale::ar),         // ar-KM
    Some(Locale::ar),         // ar-KW
    Some(Locale::ar),         // ar-LB
    Some(Locale::ar),         // ar-LY
    Some(Locale::ar),         // ar-MA
    Some(Locale::ar),         // ar-MR
    Some(Locale::ar),         // ar-OM
    Some(Locale::ar),         // ar-PS
    Some(Locale::ar),         // ar-QA
    Some(Locale::ar),         // ar-SA
    Some(Locale::ar),         // ar-SD
    Some(Locale::ar),         // ar-SO
    Some(Locale::ar),         // ar-SS
    Some(Locale::ar),         // ar-SY
    Some(Locale::ar),         // ar-TD
    Some(Locale::ar),         // ar-TN
    Some(Locale::ar),         // ar-YE
    None,                     // arn
    None,                     // as
    None,                     // asa
    None,                     // ast
    None,                     // az
    None,                     // az-Arab
    Some(Locale::az_Arab),    // az-Arab-IQ
    Some(Locale::az_Arab),    // az-Arab-TR
    None,                     // az-Cyrl
    Some(Locale::az),         // az-Latn
    None,                     // ba
    None,                     // bal
    Some(Locale::bal),        // bal-Arab
    None,                     // bal-Latn
    None,                     // bas
    None,                     // be
    Some(Locale::be),         // be-tarask
    None,                     // bem
    None,                     // bew
    None,                     // bez
    None,                     // bg
    None,                     // bgc
    None,                     // bgn
    Some(Locale::bgn),        // bgn-AE
    Some(Locale::bgn),        // bgn-AF
    Some(Locale::bgn),        // bgn-IR
    Some(Locale::bgn),        // bgn-OM
    None,                     // bho
    None,                     // blo
    None,                     // blt
    None,                     // bm
    None,                     // bm-Nkoo
    None,                     // bn
    Some(Locale::bn),         // bn-IN
    None,                     // bo
    Some(Locale::bo),         // bo-IN
    None,                     // bqi
    None,                     // br
    None,                     // brx
    None,                     // bs
    None,                     // bs-Cyrl
    Some(Locale::bs),         // bs-Latn
    None,                     // bss
    None,                     // bua
    None,                     // byn
    None,                     // ca
    Some(Locale::ca),         // ca-AD
    Some(Locale::ca),         // ca-ES-valencia
    Some(Locale::ca),         // ca-FR
    Some(Locale::ca),         // ca-IT
    None,                     // cad
    None,                     // cch
    None,                     // ccp
    Some(Locale::ccp),        // ccp-IN
    None,                     // ce
    None,                     // ceb
    None,                     // cgg
    None,                     // cho
    None,                     // chr
    None,                     // cic
    None,                     // ckb
    Some(Locale::ckb),        // ckb-IR
    None,                     // co
    None,                     // cop
    None,                     // cs
    None,                     // csw
    None,                     // cu
    None,                     // cv
    None,                     // cy
    None,                     // da
    Some(Locale::da),         // da-GL
    None,                     // dav
    None,                     // de
    Some(Locale::de),         // de-AT
    Some(Locale::de),         // de-BE
    Some(Locale::de),         // de-CH
    Some(Locale::de),         // de-IT
    Some(Locale::de),         // de-LI
    Some(Locale::de),         // de-LU
    None,                     // dje
    None,                     // doi
    None,                     // dsb
    None,                     // dua
    None,                     // dv
    None,                     // dyo
    None,                     // dz
    None,                     // ebu
    None,                     // ee
    Some(Locale::ee),         // ee-TG
    None,                     // el
    Some(Locale::el),         // el-CY
    Some(Locale::el),         // el-polyton
    None,                     // en
    Some(Locale::en),         // en-001
    Some(Locale::en_001),     // en-150
    Some(Locale::en),         // en-AE
    Some(Locale::en_001),     // en-AG
    Some(Locale::en_001),     // en-AI
    Some(Locale::en),         // en-AS
    Some(Locale::en_150),     // en-AT
    Some(Locale::en_001),     // en-AU
    Some(Locale::en_001),     // en-BB
    Some(Locale::en_150),     // en-BE
    Some(Locale::en),         // en-BI
    Some(Locale::en_001),     // en-BM
    Some(Locale::en_001),     // en-BS
    Some(Locale::en_001),     // en-BW
    Some(Locale::en_001),     // en-BZ
    Some(Locale::en),         // en-CA
    Some(Locale::en_001),     // en-CC
    Some(Locale::en_150),     // en-CH
    Some(Locale::en_001),     // en-CK
    Some(Locale::en_001),     // en-CM
    Some(Locale::en_001),     // en-CX
    Some(Locale::en_001),     // en-CY
    Some(Locale::en_150),     // en-CZ
    Some(Locale::en_150),     // en-DE
    Some(Locale::en_001),     // en-DG
    Some(Locale::en_150),     // en-DK
    Some(Locale::en_001),     // en-DM
    None,                     // en-Dsrt
    Some(Locale::en_150),     // en-EE
    Some(Locale::en_001),     // en-ER
    Some(Locale::en_150),     // en-ES
    Some(Locale::en_150),     // en-FI
    Some(Locale::en_001),     // en-FJ
    Some(Locale::en_001),     // en-FK
    Some(Locale::en_001),     // en-FM
    Some(Locale::en_150),     // en-FR
    Some(Locale::en_001),     // en-GB
    Some(Locale::en_001),     // en-GD
    Some(Locale::en_150),     // en-GE
    Some(Locale::en_001),     // en-GG
    Some(Locale::en_001),     // en-GH
    Some(Locale::en_001),     // en-GI
    Some(Locale::en_001),     // en-GM
    Some(Locale::en_001),     // en-GS
    Some(Locale::en),         // en-GU
    Some(Locale::en_001),     // en-GY
    Some(Locale::en_001),     // en-HK
    Some(Locale::en_150),     // en-HU
    Some(Locale::en_001),     // en-ID
    Some(Locale::en_001),     // en-IE
    Some(Locale::en_001),     // en-IL
    Some(Locale::en_001),     // en-IM
    Some(Locale::en_001),     // en-IN
    Some(Locale::en_001),     // en-IO
    Some(Locale::en_150),     // en-IT
    Some(Locale::en_001),     // en-JE
    Some(Locale::en_001),     // en-JM
    Some(Locale::en),         // en-JP
    Some(Locale::en_001),     // en-KE
    Some(Locale::en_001),     // en-KI
    Some(Locale::en_001),     // en-KN
    Some(Locale::en_001),     // en-KY
    Some(Locale::en_001),     // en-LC
    Some(Locale::en_001),     // en-LR
    Some(Locale::en_001),     // en-LS
    Some(Locale::en_150),     // en-LT
    Some(Locale::en_150),     // en-LV
    Some(Locale::en_001),     // en-MG
    Some(Locale::en),         // en-MH
    Some(Locale::en_001),     // en-MO
    Some(Locale::en),         // en-MP
    Some(Locale::en_001),     // en-MS
    Some(Locale::en_001),     // en-MT
    Some(Locale::en_001),     // en-MU
    Some(Locale::en_001),     // en-MV
    Some(Locale::en_001),     // en-MW
    Some(Locale::en_001),     // en-MY
    Some(Locale::en_001),     // en-NA
    Some(Locale::en_001),     // en-NF
    Some(Locale::en_001),     // en-NG
    Some(Locale::en_150),     // en-NL
    Some(Locale::en_150),     // en-NO
    Some(Locale::en_001),     // en-NR
    Some(Locale::en_001),     // en-NU
    Some(Locale::en_001),     // en-NZ
    Some(Locale::en_001),     // en-PG
    Some(Locale::en),         // en-PH
    Some(Locale::en_001),     // en-PK
    Some(Locale::en_150),     // en-PL
    Some(Locale::en_001),     // en-PN
    Some(Locale::en),         // en-PR
    Some(Locale::en_150),     // en-PT
    Some(Locale::en_001),     // en-PW
    Some(Locale::en_150),     // en-RO
    Some(Locale::en_001),     // en-RW
    Some(Locale::en_001),     // en-SB
    Some(Locale::en_001),     // en-SC
    Some(Locale::en_001),     // en-SD
    Some(Locale::en_150),     // en-SE
    Some(Locale::en_001),     // en-SG
    Some(Locale::en_001),     // en-SH
    Some(Locale::en_150),     // en-SI
    Some(Locale::en_150),     // en-SK
    Some(Locale::en_001),     // en-SL
    Some(Locale::en_001),     // en-SS
    Some(Locale::en_001),     // en-SX
    Some(Locale::en_001),     // en-SZ
    None,                     // en-Shaw
    Some(Locale::en_001),     // en-TC
    Some(Locale::en_001),     // en-TK
    Some(Locale::en_001),     // en-TO
    Some(Locale::en_001),     // en-TT
    Some(Locale::en_001),     // en-TV
    Some(Locale::en_001),     // en-TZ
    Some(Locale::en_150),     // en-UA
    Some(Locale::en_001),     // en-UG
    Some(Locale::en),         // en-UM
    Some(Locale::en_001),     // en-VC
    Some(Locale::en_001),     // en-VG
    Some(Locale::en),         // en-VI
    Some(Locale::en_001),     // en-VU
    Some(Locale::en_001),     // en-WS
    Some(Locale::en_001),     // en-ZA
    Some(Locale::en_001),     // en-ZM
    Some(Locale::en_001),     // en-ZW
    None,                     // eo
    None,                     // es
    Some(Locale::es),         // es-419
    Some(Locale::es_419),     // es-AR
    Some(Locale::es_419),     // es-BO
    Some(Locale::es_419),     // es-BR
    Some(Locale::es_419),     // es-BZ
    Some(Locale::es_419),     // es-CL
    Some(Locale::es_419),     // es-CO
    Some(Locale::es_419),     // es-CR
    Some(Locale::es_419),     // es-CU
    Some(Locale::es_419),     // es-DO
    Some(Locale::es),         // es-EA
    Some(Locale::es_419),     // es-EC
    Some(Locale::es),         // es-GQ
    Some(Locale::es_419),     // es-GT
    Some(Locale::es_419),     // es-HN
    Some(Locale::es),         // es-IC
    Some(Locale::es_419),     // es-MX
    Some(Locale::es_419),     // es-NI
    Some(Locale::es_419),     // es-PA
    Some(Locale::es_419),     // es-PE
    Some(Locale::es),         // es-PH
    Some(Locale::es_419),     // es-PR
    Some(Locale::es_419),     // es-PY
    Some(Locale::es_419),     // es-SV
    Some(Locale::es_419),     // es-US
    Some(Locale::es_419),     // es-UY
    Some(Locale::es_419),     // es-VE
    None,                     // et
    None,                     // eu
    None,                     // ewo
    None,                     // fa
    Some(Locale::fa),         // fa-AF
    None,                     // ff
    None,                     // ff-Adlm
    Some(Locale::ff_Adlm),    // ff-Adlm-BF
    Some(Locale::ff_Adlm),    // ff-Adlm-CM
    Some(Locale::ff_Adlm),    // ff-Adlm-GH
    Some(Locale::ff_Adlm),    // ff-Adlm-GM
    Some(Locale::ff_Adlm),    // ff-Adlm-GW
    Some(Locale::ff_Adlm),    // ff-Adlm-LR
    Some(Locale::ff_Adlm),    // ff-Adlm-MR
    Some(Locale::ff_Adlm),    // ff-Adlm-NE
    Some(Locale::ff_Adlm),    // ff-Adlm-NG
    Some(Locale::ff_Adlm),    // ff-Adlm-SL
    Some(Locale::ff_Adlm),    // ff-Adlm-SN
    Some(Locale::ff),         // ff-Latn
    Some(Locale::ff_Latn),    // ff-Latn-BF
    Some(Locale::ff_Latn),    // ff-Latn-CM
    Some(Locale::ff_Latn),    // ff-Latn-GH
    Some(Locale::ff_Latn),    // ff-Latn-GM
    Some(Locale::ff_Latn),    // ff-Latn-GN
    Some(Locale::ff_Latn),    // ff-Latn-GW
    Some(Locale::ff_Latn),    // ff-Latn-LR
    Some(Locale::ff_Latn),    // ff-Latn-MR
    Some(Locale::ff_Latn),    // ff-Latn-NE
    Some(Locale::ff_Latn),    // ff-Latn-NG
    Some(Locale::ff_Latn),    // ff-Latn-SL
    None,                     // fi
    None,                     // fil
    None,                     // fo
    Some(Locale::fo),         // fo-DK
    None,                     // fr
    Some(Locale::fr),         // fr-BE
    Some(Locale::fr),         // fr-BF
    Some(Locale::fr),         // fr-BI
    Some(Locale::fr),         // fr-BJ
    Some(Locale::fr),         // fr-BL
    Some(Locale::fr),         // fr-CA
    Some(Locale::fr),         // fr-CD
    Some(Locale::fr),         // fr-CF
    Some(Locale::fr),         // fr-CG
    Some(Locale::fr),         // fr-CH
    Some(Locale::fr),         // fr-CI
    Some(Locale::fr),         // fr-CM
    Some(Locale::fr),         // fr-DJ
    Some(Locale::fr),         // fr-DZ
    Some(Locale::fr),         // fr-GA
    Some(Locale::fr),         // fr-GF
    Some(Locale::fr),         // fr-GN
    Some(Locale::fr),         // fr-GP
    Some(Locale::fr),         // fr-GQ
    Some(Locale::fr),         // fr-HT
    Some(Locale::fr),         // fr-KM
    Some(Locale::fr),         // fr-LU
    Some(Locale::fr),         // fr-MA
    Some(Locale::fr),         // fr-MC
    Some(Locale::fr),         // fr-MF
    Some(Locale::fr),         // fr-MG
    Some(Locale::fr),         // fr-ML
    Some(Locale::fr),         // fr-MQ
    Some(Locale::fr),         // fr-MR
    Some(Locale::fr),         // fr-MU
    Some(Locale::fr),         // fr-NC
    Some(Locale::fr),         // fr-NE
    Some(Locale::fr),         // fr-PF
    Some(Locale::fr),         // fr-PM
    Some(Locale::fr),         // fr-RE
    Some(Locale::fr),         // fr-RW
    Some(Locale::fr),         // fr-SC
    Some(Locale::fr),         // fr-SN
    Some(Locale::fr),         // fr-SY
    Some(Locale::fr),         // fr-TD
    Some(Locale::fr),         // fr-TG
    Some(Locale::fr),         // fr-TN
    Some(Locale::fr),         // fr-VU
    Some(Locale::fr),         // fr-WF
    Some(Locale::fr),         // fr-YT
    None,                     // frr
    None,                     // fur
    None,                     // fy
    None,                     // ga
    Some(Locale::ga),         // ga-GB
    None,                     // gaa
    None,                     // gd
    None,                     // gez
    Some(Locale::gez),        // gez-ER
    None,                     // gl
    None,                     // gn
    None,                     // gsw
    Some(Locale::gsw),        // gsw-FR
    Some(Locale::gsw),        // gsw-LI
    None,                     // gu
    None,                     // guz
    None,                     // gv
    None,                     // ha
    None,                     // ha-Arab
    Some(Locale::ha_Arab),    // ha-Arab-SD
    Some(Locale::ha),         // ha-GH
    Some(Locale::ha),         // ha-NE
    None,                     // haw
    None,                     // he
    None,                     // hi
    Some(Locale::en_IN),      // hi-Latn
    None,                     // hnj
    Some(Locale::hnj),        // hnj-Hmnp
    None,                     // hr
    Some(Locale::hr),         // hr-BA
    None,                     // hsb
    Some(Locale::fr_HT),      // ht
    None,                     // hu
    None,                     // hy
    None,                     // ia
    None,                     // id
    None,                     // ie
    None,                     // ig
    None,                     // ii
    None,                     // io
    None,                     // is
    None,                     // it
    Some(Locale::it),         // it-CH
    Some(Locale::it),         // it-SM
    Some(Locale::it),         // it-VA
    None,                     // iu
    None,                     // iu-Latn
    None,                     // ja
    None,                     // jbo
    None,                     // jgo
    None,                     // jmc
    None,                     // jv
    None,                     // ka
    None,                     // kaa
    Some(Locale::kaa),        // kaa-Cyrl
    None,                     // kaa-Latn
    None,                     // kab
    None,                     // kaj
    None,                     // kam
    None,                     // kcg
    None,                     // kde
    None,                     // kea
    None,                     // kek
    None,                     // ken
    None,                     // kgp
    None,                     // khq
    None,                     // ki
    None,                     // kk
    None,                     // kk-Arab
    Some(Locale::kk),         // kk-Cyrl
    Some(Locale::kk),         // kk-KZ
    None,                     // kkj
    None,                     // kl
    None,                     // kln
    None,                     // km
    None,                     // kn
    None,                     // ko
    Some(Locale::ko),         // ko-CN
    Some(Locale::ko),         // ko-KP
    None,                     // kok
    Some(Locale::kok),        // kok-Deva
    None,                     // kok-Latn
    None,                     // kpe
    Some(Locale::kpe),        // kpe-GN
    None,                     // ks
    Some(Locale::ks),         // ks-Arab
    None,                     // ks-Deva
    None,                     // ksb
    None,                     // ksf
    None,                     // ksh
    None,                     // ku
    None,                     // ku-Arab
    Some(Locale::ku_Arab),    // ku-Arab-IR
    Some(Locale::ku),         // ku-Latn
    Some(Locale::ku_Latn),    // ku-Latn-IQ
    Some(Locale::ku_Latn),    // ku-Latn-SY
    Some(Locale::ku),         // ku-TR
    None,                     // kw
    None,                     // kxv
    None,                     // kxv-Deva
    Some(Locale::kxv),        // kxv-Latn
    None,                     // kxv-Orya
    None,                     // kxv-Telu
    None,                     // ky
    None,                     // la
    None,                     // lag
    None,                     // lb
    None,                     // lg
    None,                     // lij
    None,                     // lkt
    None,                     // lld
    None,                     // lmo
    None,                     // ln
    Some(Locale::ln),         // ln-AO
    Some(Locale::ln),         // ln-CF
    Some(Locale::ln),         // ln-CG
    None,                     // lo
    None,                     // lrc
    Some(Locale::lrc),        // lrc-IQ
    None,                     // lt
    None,                     // ltg
    None,                     // lu
    None,                     // luo
    None,                     // luy
    None,                     // lv
    None,                     // lzz
    None,                     // mai
    None,                     // mas
    Some(Locale::mas),        // mas-TZ
    None,                     // mdf
    None,                     // mer
    None,                     // mfe
    None,                     // mg
    None,                     // mgh
    None,                     // mgo
    None,                     // mhn
    None,                     // mi
    None,                     // mic
    None,                     // mk
    None,                     // ml
    None,                     // mn
    None,                     // mn-Mong
    Some(Locale::mn_Mong),    // mn-Mong-MN
    None,                     // mni
    Some(Locale::mni),        // mni-Beng
    None,                     // mni-Mtei
    None,                     // moh
    None,                     // mr
    None,                     // ms
    None,                     // ms-Arab
    Some(Locale::ms_Arab),    // ms-Arab-BN
    Some(Locale::ms),         // ms-BN
    Some(Locale::ms),         // ms-ID
    Some(Locale::ms),         // ms-SG
    None,                     // mt
    None,                     // mua
    None,                     // mus
    None,                     // mww
    Some(Locale::mww),        // mww-Hmnp
    None,                     // my
    None,                     // myv
    None,                     // mzn
    None,                     // naq
    Some(Locale::no),         // nb
    Some(Locale::nb),         // nb-SJ
    None,                     // nd
    None,                     // nds
    Some(Locale::nds),        // nds-NL
    None,                     // ne
    Some(Locale::ne),         // ne-IN
    None,                     // nl
    Some(Locale::nl),         // nl-AW
    Some(Locale::nl),         // nl-BE
    Some(Locale::nl),         // nl-BQ
    Some(Locale::nl),         // nl-CW
    Some(Locale::nl),         // nl-SR
    Some(Locale::nl),         // nl-SX
    None,                     // nmg
    Some(Locale::no),         // nn
    None,                     // nnh
    None,                     // no
    None,                     // nqo
    None,                     // nr
    None,                     // nso
    None,                     // nus
    None,                     // nv
    None,                     // ny
    None,                     // nyn
    None,                     // oc
    Some(Locale::oc),         // oc-ES
    None,                     // oka
    Some(Locale::oka),        // oka-US
    None,                     // om
    Some(Locale::om),         // om-KE
    None,                     // or
    None,                     // os
    Some(Locale::os),         // os-RU
    None,                     // osa
    None,                     // pa
    None,                     // pa-Arab
    Some(Locale::pa),         // pa-Guru
    None,                     // pap
    Some(Locale::pap),        // pap-AW
    None,                     // pcm
    None,                     // pi
    Some(Locale::pi),         // pi-Latn
    None,                     // pis
    None,                     // pl
    None,                     // pms
    None,                     // prg
    None,                     // ps
    Some(Locale::ps),         // ps-PK
    None,                     // pt
    Some(Locale::pt_PT),      // pt-AO
    Some(Locale::pt_PT),      // pt-CH
    Some(Locale::pt_PT),      // pt-CV
    Some(Locale::pt_PT),      // pt-GQ
    Some(Locale::pt_PT),      // pt-GW
    Some(Locale::pt_PT),      // pt-LU
    Some(Locale::pt_PT),      // pt-MO
    Some(Locale::pt_PT),      // pt-MZ
    Some(Locale::pt),         // pt-PT
    Some(Locale::pt_PT),      // pt-ST
    Some(Locale::pt_PT),      // pt-TL
    None,                     // qu
    Some(Locale::qu),         // qu-BO
    Some(Locale::qu),         // qu-EC
    None,                     // quc
    None,                     // raj
    None,                     // rhg
    Some(Locale::rhg),        // rhg-Rohg
    Some(Locale::rhg_Rohg),   // rhg-Rohg-BD
    None,                     // rif
    None,                     // rm
    None,                     // rn
    None,                     // ro
    Some(Locale::ro),         // ro-MD
    None,                     // rof
    None,                     // ru
    Some(Locale::ru),         // ru-BY
    Some(Locale::ru),         // ru-KG
    Some(Locale::ru),         // ru-KZ
    Some(Locale::ru),         // ru-MD
    Some(Locale::ru),         // ru-UA
    None,                     // rw
    None,                     // rwk
    None,                     // sa
    None,                     // sah
    None,                     // saq
    None,                     // sat
    None,                     // sat-Deva
    Some(Locale::sat),        // sat-Olck
    None,                     // sbp
    None,                     // sc
    None,                     // scn
    None,                     // sd
    Some(Locale::sd),         // sd-Arab
    None,                     // sd-Deva
    None,                     // sdh
    Some(Locale::sdh),        // sdh-IQ
    None,                     // se
    Some(Locale::se),         // se-FI
    Some(Locale::se),         // se-SE
    None,                     // seh
    None,                     // ses
    None,                     // sg
    None,                     // sgs
    None,                     // shi
    None,                     // shi-Latn
    Some(Locale::shi),        // shi-Tfng
    None,                     // shn
    Some(Locale::shn),        // shn-TH
    None,                     // si
    None,                     // sid
    None,                     // sk
    None,                     // skr
    None,                     // sl
    None,                     // sma
    Some(Locale::sma),        // sma-NO
    None,                     // smj
    Some(Locale::smj),        // smj-NO
    None,                     // smn
    None,                     // sms
    None,                     // sn
    None,                     // so
    Some(Locale::so),         // so-DJ
    Some(Locale::so),         // so-ET
    Some(Locale::so),         // so-KE
    None,                     // sq
    Some(Locale::sq),         // sq-MK
    Some(Locale::sq),         // sq-XK
    None,                     // sr
    Some(Locale::sr),         // sr-Cyrl
    Some(Locale::sr_Cyrl),    // sr-Cyrl-BA
    Some(Locale::sr_Cyrl),    // sr-Cyrl-ME
    Some(Locale::sr_Cyrl),    // sr-Cyrl-XK
    None,                     // sr-Latn
    Some(Locale::sr_Latn),    // sr-Latn-BA
    Some(Locale::sr_Latn),    // sr-Latn-ME
    Some(Locale::sr_Latn),    // sr-Latn-XK
    None,                     // ss
    Some(Locale::ss),         // ss-SZ
    None,                     // ssy
    None,                     // st
    Some(Locale::st),         // st-LS
    None,                     // su
    Some(Locale::su),         // su-Latn
    None,                     // suz
    Some(Locale::suz),        // suz-Deva
    None,                     // suz-Sunu
    None,                     // sv
    Some(Locale::sv),         // sv-AX
    Some(Locale::sv),         // sv-FI
    None,                     // sw
    Some(Locale::sw),         // sw-CD
    Some(Locale::sw),         // sw-KE
    Some(Locale::sw),         // sw-UG
    None,                     // syr
    Some(Locale::syr),        // syr-SY
    None,                     // szl
    None,                     // ta
    Some(Locale::ta),         // ta-LK
    Some(Locale::ta),         // ta-MY
    Some(Locale::ta),         // ta-SG
    None,                     // te
    None,                     // teo
    Some(Locale::teo),        // teo-KE
    None,                     // tg
    None,                     // th
    None,                     // ti
    Some(Locale::ti),         // ti-ER
    None,                     // tig
    None,                     // tk
    None,                     // tn
    Some(Locale::tn),         // tn-BW
    None,                     // to
    None,                     // tok
    None,                     // tpi
    None,                     // tr
    Some(Locale::tr),         // tr-CY
    None,                     // trv
    None,                     // trw
    None,                     // ts
    None,                     // tt
    None,                     // twq
    None,                     // tyv
    None,                     // tzm
    None,                     // ug
    None,                     // uk
    None,                     // und
    None,                     // ur
    Some(Locale::ur),         // ur-IN
    None,                     // uz
    None,                     // uz-Arab
    None,                     // uz-Cyrl
    Some(Locale::uz),         // uz-Latn
    None,                     // vai
    None,                     // vai-Latn
    Some(Locale::vai),        // vai-Vaii
    None,                     // ve
    None,                     // vec
    None,                     // vi
    None,                     // vmw
    None,                     // vo
    None,                     // vun
    None,                     // wa
    None,                     // wae
    None,                     // wal
    None,                     // wbp
    None,                     // wo
    None,                     // xh
    None,                     // xnr
    None,                     // xog
    None,                     // yav
    None,                     // yi
    None,                     // yo
    Some(Locale::yo),         // yo-BJ
    None,                     // yrl
    Some(Locale::yrl),        // yrl-CO
    Some(Locale::yrl),        // yrl-VE
    None,                     // yue
    None,                     // yue-Hans
    Some(Locale::yue),        // yue-Hant
    Some(Locale::yue_Hant),   // yue-Hant-CN
    Some(Locale::yue_Hant),   // yue-Hant-MO
    None,                     // za
    None,                     // zgh
    None,                     // zh
    Some(Locale::zh),         // zh-Hans
    Some(Locale::zh_Hans),    // zh-Hans-HK
    Some(Locale::zh_Hans),    // zh-Hans-MO
    Some(Locale::zh_Hans),    // zh-Hans-MY
    Some(Locale::zh_Hans),    // zh-Hans-SG
    None,                     // zh-Hant
    Some(Locale::zh_Hant),    // zh-Hant-HK
    Some(Locale::zh_Hant_HK), // zh-Hant-MO
    Some(Locale::zh_Hant),    // zh-Hant-MY
    None,                     // zh-Latn
    None,                     // zu
];
