// @generated by locale-dev from CLDR 48.2.3. Do not edit by hand;
// run `cargo run -p locale-dev` instead.

//! Number symbols of every locale.

use crate::data::{Grouping, NumberSymbols};
static DIGITS_0: [char; 10] = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'];
static DIGITS_1: [char; 10] = ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'];
static DIGITS_2: [char; 10] = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
static DIGITS_3: [char; 10] = ['०', '१', '२', '३', '४', '५', '६', '७', '८', '९'];
static DIGITS_4: [char; 10] = ['𑄶', '𑄷', '𑄸', '𑄹', '𑄺', '𑄻', '𑄼', '𑄽', '𑄾', '𑄿'];
static DIGITS_5: [char; 10] = ['༠', '༡', '༢', '༣', '༤', '༥', '༦', '༧', '༨', '༩'];
static DIGITS_6: [char; 10] = ['𞥐', '𞥑', '𞥒', '𞥓', '𞥔', '𞥕', '𞥖', '𞥗', '𞥘', '𞥙'];
static DIGITS_7: [char; 10] = ['𞅀', '𞅁', '𞅂', '𞅃', '𞅄', '𞅅', '𞅆', '𞅇', '𞅈', '𞅉'];
static DIGITS_8: [char; 10] = ['꯰', '꯱', '꯲', '꯳', '꯴', '꯵', '꯶', '꯷', '꯸', '꯹'];
static DIGITS_9: [char; 10] = ['၀', '၁', '၂', '၃', '၄', '၅', '၆', '၇', '၈', '၉'];
static DIGITS_10: [char; 10] = ['߀', '߁', '߂', '߃', '߄', '߅', '߆', '߇', '߈', '߉'];
static DIGITS_11: [char; 10] = ['᱐', '᱑', '᱒', '᱓', '᱔', '᱕', '᱖', '᱗', '᱘', '᱙'];
static NUMBERS_0: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_1: NumberSymbols = NumberSymbols {
    decimal: ",",
    group: "\u{a0}",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_2: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "\u{200e}-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_3: NumberSymbols = NumberSymbols {
    decimal: "٫",
    group: "٬",
    minus_sign: "\u{61c}-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_0),
};
static NUMBERS_4: NumberSymbols = NumberSymbols {
    decimal: ",",
    group: ".",
    minus_sign: "\u{200e}-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_5: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 2,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_1),
};
static NUMBERS_6: NumberSymbols = NumberSymbols {
    decimal: ",",
    group: ".",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_7: NumberSymbols = NumberSymbols {
    decimal: "٫",
    group: "٬",
    minus_sign: "\u{200e}-\u{200e}",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_2),
};
static NUMBERS_8: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: "\u{a0}",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_9: NumberSymbols = NumberSymbols {
    decimal: ",",
    group: "\u{a0}",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 2,
    },
    digits: None,
};
static NUMBERS_10: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_3),
};
static NUMBERS_11: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 2,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_12: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 2,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_4),
};
static NUMBERS_13: NumberSymbols = NumberSymbols {
    decimal: "٫",
    group: "٬",
    minus_sign: "\u{200f}-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_0),
};
static NUMBERS_14: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: "'",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_15: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 2,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_5),
};
static NUMBERS_16: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 3,
    },
    digits: None,
};
static NUMBERS_17: NumberSymbols = NumberSymbols {
    decimal: ",",
    group: "\u{202f}",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_18: NumberSymbols = NumberSymbols {
    decimal: ",",
    group: ".",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 2,
    },
    digits: None,
};
static NUMBERS_19: NumberSymbols = NumberSymbols {
    decimal: ",",
    group: "\u{a0}",
    minus_sign: "−",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 2,
    },
    digits: None,
};
static NUMBERS_20: NumberSymbols = NumberSymbols {
    decimal: ",",
    group: ".",
    minus_sign: "−",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_21: NumberSymbols = NumberSymbols {
    decimal: "٫",
    group: "٬",
    minus_sign: "\u{200e}−",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_2),
};
static NUMBERS_22: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: "⹁",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_6),
};
static NUMBERS_23: NumberSymbols = NumberSymbols {
    decimal: ",",
    group: "\u{a0}",
    minus_sign: "−",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_24: NumberSymbols = NumberSymbols {
    decimal: ",",
    group: "'",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_25: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: "'",
    minus_sign: "−",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: None,
};
static NUMBERS_26: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_7),
};
static NUMBERS_27: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: "'",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 2,
    },
    digits: None,
};
static NUMBERS_28: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_1),
};
static NUMBERS_29: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_8),
};
static NUMBERS_30: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 2,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_3),
};
static NUMBERS_31: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_9),
};
static NUMBERS_32: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: "،",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_10),
};
static NUMBERS_33: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: ",",
    minus_sign: "-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_11),
};
static NUMBERS_34: NumberSymbols = NumberSymbols {
    decimal: ".",
    group: "٬",
    minus_sign: "\u{61c}-",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 1,
    },
    digits: Some(&DIGITS_0),
};
static NUMBERS_35: NumberSymbols = NumberSymbols {
    decimal: ",",
    group: ".",
    minus_sign: "−",
    grouping: Grouping {
        primary: 3,
        secondary: 3,
        min_grouping_digits: 2,
    },
    digits: None,
};
static NUMBERS_36: NumberSymbols = NumberSymbols {
    decimal: ",",
    group: "\u{a0}",
    minus_sign: "-",
    grouping: Grouping {
        primary: 2,
        secondary: 2,
        min_grouping_digits: 1,
    },
    digits: None,
};

pub(crate) static NUMBER_SYMBOLS: [&NumberSymbols; 766] = [
    &NUMBERS_0,  // aa
    &NUMBERS_0,  // aa-DJ
    &NUMBERS_0,  // aa-ER
    &NUMBERS_0,  // ab
    &NUMBERS_1,  // af
    &NUMBERS_1,  // af-NA
    &NUMBERS_1,  // agq
    &NUMBERS_0,  // ak
    &NUMBERS_0,  // am
    &NUMBERS_0,  // an
    &NUMBERS_0,  // ann
    &NUMBERS_0,  // apc
    &NUMBERS_2,  // ar
    &NUMBERS_2,  // ar-AE
    &NUMBERS_3,  // ar-BH
    &NUMBERS_3,  // ar-DJ
    &NUMBERS_4,  // ar-DZ
    &NUMBERS_3,  // ar-EG
    &NUMBERS_2,  // ar-EH
    &NUMBERS_3,  // ar-ER
    &NUMBERS_3,  // ar-IL
    &NUMBERS_3,  // ar-IQ
    &NUMBERS_3,  // ar-JO
    &NUMBERS_3,  // ar-KM
    &NUMBERS_3,  // ar-KW
    &NUMBERS_3,  // ar-LB
    &NUMBERS_4,  // ar-LY
    &NUMBERS_4,  // ar-MA
    &NUMBERS_3,  // ar-MR
    &NUMBERS_3,  // ar-OM
    &NUMBERS_3,  // ar-PS
    &NUMBERS_3,  // ar-QA
    &NUMBERS_3,  // ar-SA
    &NUMBERS_3,  // ar-SD
    &NUMBERS_3,  // ar-SO
    &NUMBERS_3,  // ar-SS
    &NUMBERS_3,  // ar-SY
    &NUMBERS_3,  // ar-TD
    &NUMBERS_4,  // ar-TN
    &NUMBERS_3,  // ar-YE
    &NUMBERS_0,  // arn
    &NUMBERS_5,  // as
    &NUMBERS_0,  // asa
    &NUMBERS_6,  // ast
    &NUMBERS_6,  // az
    &NUMBERS_7,  // az-Arab
    &NUMBERS_7,  // az-Arab-IQ
    &NUMBERS_7,  // az-Arab-TR
    &NUMBERS_6,  // az-Cyrl
    &NUMBERS_6,  // az-Latn
    &NUMBERS_8,  // ba
    &NUMBERS_0,  // bal
    &NUMBERS_0,  // bal-Arab
    &NUMBERS_0,  // bal-Latn
    &NUMBERS_1,  // bas
    &NUMBERS_9,  // be
    &NUMBERS_9,  // be-tarask
    &NUMBERS_0,  // bem
    &NUMBERS_0,  // bew
    &NUMBERS_0,  // bez
    &NUMBERS_9,  // bg
    &NUMBERS_10, // bgc
    &NUMBERS_7,  // bgn
    &NUMBERS_7,  // bgn-AE
    &NUMBERS_7,  // bgn-AF
    &NUMBERS_7,  // bgn-IR
    &NUMBERS_7,  // bgn-OM
    &NUMBERS_10, // bho
    &NUMBERS_1,  // blo
    &NUMBERS_0,  // blt
    &NUMBERS_0,  // bm
    &NUMBERS_0,  // bm-Nkoo
    &NUMBERS_5,  // bn
    &NUMBERS_5,  // bn-IN
    &NUMBERS_0,  // bo
    &NUMBERS_0,  // bo-IN
    &NUMBERS_0,  // bqi
    &NUMBERS_1,  // br
    &NUMBERS_11, // brx
    &NUMBERS_6,  // bs
    &NUMBERS_6,  // bs-Cyrl
    &NUMBERS_6,  // bs-Latn
    &NUMBERS_0,  // bss
    &NUMBERS_1,  // bua
    &NUMBERS_0,  // byn
    &NUMBERS_6,  // ca
    &NUMBERS_6,  // ca-AD
    &NUMBERS_6,  // ca-ES-valencia
    &NUMBERS_6,  // ca-FR
    &NUMBERS_6,  // ca-IT
    &NUMBERS_0,  // cad
    &NUMBERS_0,  // cch
    &NUMBERS_12, // ccp
    &NUMBERS_12, // ccp-IN
    &NUMBERS_0,  // ce
    &NUMBERS_0,  // ceb
    &NUMBERS_0,  // cgg
    &NUMBERS_0,  // cho
    &NUMBERS_0,  // chr
    &NUMBERS_0,  // cic
    &NUMBERS_13, // ckb
    &NUMBERS_13, // ckb-IR
    &NUMBERS_0,  // co
    &NUMBERS_0,  // cop
    &NUMBERS_1,  // cs
    &NUMBERS_0,  // csw
    &NUMBERS_0,  // cu
    &NUMBERS_1,  // cv
    &NUMBERS_0,  // cy
    &NUMBERS_6,  // da
    &NUMBERS_6,  // da-GL
    &NUMBERS_0,  // dav
    &NUMBERS_6,  // de
    &NUMBERS_1,  // de-AT
    &NUMBERS_6,  // de-BE
    &NUMBERS_14, // de-CH
    &NUMBERS_6,  // de-IT
    &NUMBERS_14, // de-LI
    &NUMBERS_6,  // de-LU
    &NUMBERS_8,  // dje
    &NUMBERS_0,  // doi
    &NUMBERS_6,  // dsb
    &NUMBERS_1,  // dua
    &NUMBERS_0,  // dv
    &NUMBERS_1,  // dyo
    &NUMBERS_15, // dz
    &NUMBERS_0,  // ebu
    &NUMBERS_16, // ee
    &NUMBERS_16, // ee-TG
    &NUMBERS_6,  // el
    &NUMBERS_6,  // el-CY
    &NUMBERS_6,  // el-polyton
    &NUMBERS_0,  // en
    &NUMBERS_0,  // en-001
    &NUMBERS_0,  // en-150
    &NUMBERS_0,  // en-AE
    &NUMBERS_0,  // en-AG
    &NUMBERS_0,  // en-AI
    &NUMBERS_0,  // en-AS
    &NUMBERS_6,  // en-AT
    &NUMBERS_0,  // en-AU
    &NUMBERS_0,  // en-BB
    &NUMBERS_6,  // en-BE
    &NUMBERS_0,  // en-BI
    &NUMBERS_0,  // en-BM
    &NUMBERS_0,  // en-BS
    &NUMBERS_0,  // en-BW
    &NUMBERS_0,  // en-BZ
    &NUMBERS_0,  // en-CA
    &NUMBERS_0,  // en-CC
    &NUMBERS_14, // en-CH
    &NUMBERS_0,  // en-CK
    &NUMBERS_0,  // en-CM
    &NUMBERS_0,  // en-CX
    &NUMBERS_0,  // en-CY
    &NUMBERS_1,  // en-CZ
    &NUMBERS_6,  // en-DE
    &NUMBERS_0,  // en-DG
    &NUMBERS_6,  // en-DK
    &NUMBERS_0,  // en-DM
    &NUMBERS_0,  // en-Dsrt
    &NUMBERS_1,  // en-EE
    &NUMBERS_0,  // en-ER
    &NUMBERS_6,  // en-ES
    &NUMBERS_1,  // en-FI
    &NUMBERS_0,  // en-FJ
    &NUMBERS_0,  // en-FK
    &NUMBERS_0,  // en-FM
    &NUMBERS_17, // en-FR
    &NUMBERS_0,  // en-GB
    &NUMBERS_0,  // en-GD
    &NUMBERS_17, // en-GE
    &NUMBERS_0,  // en-GG
    &NUMBERS_0,  // en-GH
    &NUMBERS_0,  // en-GI
    &NUMBERS_0,  // en-GM
    &NUMBERS_0,  // en-GS
    &NUMBERS_0,  // en-GU
    &NUMBERS_0,  // en-GY
    &NUMBERS_0,  // en-HK
    &NUMBERS_1,  // en-HU
    &NUMBERS_6,  // en-ID
    &NUMBERS_0,  // en-IE
    &NUMBERS_0,  // en-IL
    &NUMBERS_0,  // en-IM
    &NUMBERS_11, // en-IN
    &NUMBERS_0,  // en-IO
    &NUMBERS_6,  // en-IT
    &NUMBERS_0,  // en-JE
    &NUMBERS_0,  // en-JM
    &NUMBERS_0,  // en-JP
    &NUMBERS_0,  // en-KE
    &NUMBERS_0,  // en-KI
    &NUMBERS_0,  // en-KN
    &NUMBERS_0,  // en-KY
    &NUMBERS_0,  // en-LC
    &NUMBERS_0,  // en-LR
    &NUMBERS_0,  // en-LS
    &NUMBERS_1,  // en-LT
    &NUMBERS_1,  // en-LV
    &NUMBERS_0,  // en-MG
    &NUMBERS_0,  // en-MH
    &NUMBERS_0,  // en-MO
    &NUMBERS_0,  // en-MP
    &NUMBERS_0,  // en-MS
    &NUMBERS_0,  // en-MT
    &NUMBERS_0,  // en-MU
    &NUMBERS_0,  // en-MV
    &NUMBERS_0,  // en-MW
    &NUMBERS_0,  // en-MY
    &NUMBERS_0,  // en-NA
    &NUMBERS_0,  // en-NF
    &NUMBERS_0,  // en-NG
    &NUMBERS_6,  // en-NL
    &NUMBERS_1,  // en-NO
    &NUMBERS_0,  // en-NR
    &NUMBERS_0,  // en-NU
    &NUMBERS_0,  // en-NZ
    &NUMBERS_0,  // en-PG
    &NUMBERS_0,  // en-PH
    &NUMBERS_0,  // en-PK
    &NUMBERS_6,  // en-PL
    &NUMBERS_0,  // en-PN
    &NUMBERS_0,  // en-PR
    &NUMBERS_1,  // en-PT
    &NUMBERS_0,  // en-PW
    &NUMBERS_6,  // en-RO
    &NUMBERS_0,  // en-RW
    &NUMBERS_0,  // en-SB
    &NUMBERS_0,  // en-SC
    &NUMBERS_0,  // en-SD
    &NUMBERS_1,  // en-SE
    &NUMBERS_0,  // en-SG
    &NUMBERS_0,  // en-SH
    &NUMBERS_6,  // en-SI
    &NUMBERS_1,  // en-SK
    &NUMBERS_0,  // en-SL
    &NUMBERS_0,  // en-SS
    &NUMBERS_0,  // en-SX
    &NUMBERS_0,  // en-SZ
    &NUMBERS_0,  // en-Shaw
    &NUMBERS_0,  // en-TC
    &NUMBERS_0,  // en-TK
    &NUMBERS_0,  // en-TO
    &NUMBERS_0,  // en-TT
    &NUMBERS_0,  // en-TV
    &NUMBERS_0,  // en-TZ
    &NUMBERS_1,  // en-UA
    &NUMBERS_0,  // en-UG
    &NUMBERS_0,  // en-UM
    &NUMBERS_0,  // en-VC
    &NUMBERS_0,  // en-VG
    &NUMBERS_0,  // en-VI
    &NUMBERS_0,  // en-VU
    &NUMBERS_0,  // en-WS
    &NUMBERS_1,  // en-ZA
    &NUMBERS_0,  // en-ZM
    &NUMBERS_0,  // en-ZW
    &NUMBERS_17, // eo
    &NUMBERS_18, // es
    &NUMBERS_0,  // es-419
    &NUMBERS_6,  // es-AR
    &NUMBERS_6,  // es-BO
    &NUMBERS_0,  // es-BR
    &NUMBERS_0,  // es-BZ
    &NUMBERS_6,  // es-CL
    &NUMBERS_6,  // es-CO
    &NUMBERS_1,  // es-CR
    &NUMBERS_0,  // es-CU
    &NUMBERS_0,  // es-DO
    &NUMBERS_18, // es-EA
    &NUMBERS_6,  // es-EC
    &NUMBERS_18, // es-GQ
    &NUMBERS_0,  // es-GT
    &NUMBERS_0,  // es-HN
    &NUMBERS_18, // es-IC
    &NUMBERS_0,  // es-MX
    &NUMBERS_0,  // es-NI
    &NUMBERS_0,  // es-PA
    &NUMBERS_0,  // es-PE
    &NUMBERS_18, // es-PH
    &NUMBERS_0,  // es-PR
    &NUMBERS_6,  // es-PY
    &NUMBERS_0,  // es-SV
    &NUMBERS_0,  // es-US
    &NUMBERS_6,  // es-UY
    &NUMBERS_6,  // es-VE
    &NUMBERS_19, // et
    &NUMBERS_20, // eu
    &NUMBERS_1,  // ewo
    &NUMBERS_21, // fa
    &NUMBERS_21, // fa-AF
    &NUMBERS_1,  // ff
    &NUMBERS_22, // ff-Adlm
    &NUMBERS_22, // ff-Adlm-BF
    &NUMBERS_22, // ff-Adlm-CM
    &NUMBERS_22, // ff-Adlm-GH
    &NUMBERS_22, // ff-Adlm-GM
    &NUMBERS_22, // ff-Adlm-GW
    &NUMBERS_22, // ff-Adlm-LR
    &NUMBERS_22, // ff-Adlm-MR
    &NUMBERS_22, // ff-Adlm-NE
    &NUMBERS_22, // ff-Adlm-NG
    &NUMBERS_22, // ff-Adlm-SL
    &NUMBERS_22, // ff-Adlm-SN
    &NUMBERS_1,  // ff-Latn
    &NUMBERS_1,  // ff-Latn-BF
    &NUMBERS_1,  // ff-Latn-CM
    &NUMBERS_1,  // ff-Latn-GH
    &NUMBERS_1,  // ff-Latn-GM
    &NUMBERS_1,  // ff-Latn-GN
    &NUMBERS_1,  // ff-Latn-GW
    &NUMBERS_1,  // ff-Latn-LR
    &NUMBERS_1,  // ff-Latn-MR
    &NUMBERS_1,  // ff-Latn-NE
    &NUMBERS_1,  // ff-Latn-NG
    &NUMBERS_1,  // ff-Latn-SL
    &NUMBERS_23, // fi
    &NUMBERS_0,  // fil
    &NUMBERS_20, // fo
    &NUMBERS_20, // fo-DK
    &NUMBERS_17, // fr
    &NUMBERS_17, // fr-BE
    &NUMBERS_17, // fr-BF
    &NUMBERS_17, // fr-BI
    &NUMBERS_17, // fr-BJ
    &NUMBERS_17, // fr-BL
    &NUMBERS_1,  // fr-CA
    &NUMBERS_17, // fr-CD
    &NUMBERS_17, // fr-CF
    &NUMBERS_17, // fr-CG
    &NUMBERS_24, // fr-CH
    &NUMBERS_17, // fr-CI
    &NUMBERS_17, // fr-CM
    &NUMBERS_17, // fr-DJ
    &NUMBERS_17, // fr-DZ
    &NUMBERS_17, // fr-GA
    &NUMBERS_17, // fr-GF
    &NUMBERS_17, // fr-GN
    &NUMBERS_17, // fr-GP
    &NUMBERS_17, // fr-GQ
    &NUMBERS_17, // fr-HT
    &NUMBERS_17, // fr-KM
    &NUMBERS_6,  // fr-LU
    &NUMBERS_6,  // fr-MA
    &NUMBERS_17, // fr-MC
    &NUMBERS_17, // fr-MF
    &NUMBERS_17, // fr-MG
    &NUMBERS_17, // fr-ML
    &NUMBERS_17, // fr-MQ
    &NUMBERS_17, // fr-MR
    &NUMBERS_17, // fr-MU
    &NUMBERS_17, // fr-NC
    &NUMBERS_17, // fr-NE
    &NUMBERS_17, // fr-PF
    &NUMBERS_17, // fr-PM
    &NUMBERS_17, // fr-RE
    &NUMBERS_17, // fr-RW
    &NUMBERS_17, // fr-SC
    &NUMBERS_17, // fr-SN
    &NUMBERS_17, // fr-SY
    &NUMBERS_17, // fr-TD
    &NUMBERS_17, // fr-TG
    &NUMBERS_17, // fr-TN
    &NUMBERS_17, // fr-VU
    &NUMBERS_17, // fr-WF
    &NUMBERS_17, // fr-YT
    &NUMBERS_0,  // frr
    &NUMBERS_6,  // fur
    &NUMBERS_6,  // fy
    &NUMBERS_0,  // ga
    &NUMBERS_0,  // ga-GB
    &NUMBERS_0,  // gaa
    &NUMBERS_0,  // gd
    &NUMBERS_0,  // gez
    &NUMBERS_0,  // gez-ER
    &NUMBERS_6,  // gl
    &NUMBERS_0,  // gn
    &NUMBERS_25, // gsw
    &NUMBERS_25, // gsw-FR
    &NUMBERS_25, // gsw-LI
    &NUMBERS_11, // gu
    &NUMBERS_0,  // guz
    &NUMBERS_0,  // gv
    &NUMBERS_0,  // ha
    &NUMBERS_0,  // ha-Arab
    &NUMBERS_0,  // ha-Arab-SD
    &NUMBERS_0,  // ha-GH
    &NUMBERS_0,  // ha-NE
    &NUMBERS_0,  // haw
    &NUMBERS_2,  // he
    &NUMBERS_11, // hi
    &NUMBERS_11, // hi-Latn
    &NUMBERS_26, // hnj
    &NUMBERS_26, // hnj-Hmnp
    &NUMBERS_20, // hr
    &NUMBERS_20, // hr-BA
    &NUMBERS_6,  // hsb
    &NUMBERS_1,  // ht
    &NUMBERS_9,  // hu
    &NUMBERS_9,  // hy
    &NUMBERS_18, // ia
    &NUMBERS_6,  // id
    &NUMBERS_9,  // ie
    &NUMBERS_0,  // ig
    &NUMBERS_0,  // ii
    &NUMBERS_0,  // io
    &NUMBERS_6,  // is
    &NUMBERS_18, // it
    &NUMBERS_27, // it-CH
    &NUMBERS_18, // it-SM
    &NUMBERS_18, // it-VA
    &NUMBERS_0,  // iu
    &NUMBERS_0,  // iu-Latn
    &NUMBERS_0,  // ja
    &NUMBERS_0,  // jbo
    &NUMBERS_6,  // jgo
    &NUMBERS_0,  // jmc
    &NUMBERS_6,  // jv
    &NUMBERS_9,  // ka
    &NUMBERS_0,  // kaa
    &NUMBERS_0,  // kaa-Cyrl
    &NUMBERS_0,  // kaa-Latn
    &NUMBERS_1,  // kab
    &NUMBERS_0,  // kaj
    &NUMBERS_0,  // kam
    &NUMBERS_0,  // kcg
    &NUMBERS_0,  // kde
    &NUMBERS_1,  // kea
    &NUMBERS_0,  // kek
    &NUMBERS_0,  // ken
    &NUMBERS_6,  // kgp
    &NUMBERS_8,  // khq
    &NUMBERS_0,  // ki
    &NUMBERS_1,  // kk
    &NUMBERS_0,  // kk-Arab
    &NUMBERS_1,  // kk-Cyrl
    &NUMBERS_1,  // kk-KZ
    &NUMBERS_6,  // kkj
    &NUMBERS_6,  // kl
    &NUMBERS_0,  // kln
    &NUMBERS_0,  // km
    &NUMBERS_0,  // kn
    &NUMBERS_0,  // ko
    &NUMBERS_0,  // ko-CN
    &NUMBERS_0,  // ko-KP
    &NUMBERS_11, // kok
    &NUMBERS_11, // kok-Deva
    &NUMBERS_11, // kok-Latn
    &NUMBERS_0,  // kpe
    &NUMBERS_0,  // kpe-GN
    &NUMBERS_7,  // ks
    &NUMBERS_7,  // ks-Arab
    &NUMBERS_0,  // ks-Deva
    &NUMBERS_0,  // ksb
    &NUMBERS_1,  // ksf
    &NUMBERS_23, // ksh
    &NUMBERS_6,  // ku
    &NUMBERS_0,  // ku-Arab
    &NUMBERS_0,  // ku-Arab-IR
    &NUMBERS_6,  // ku-Latn
    &NUMBERS_6,  // ku-Latn-IQ
    &NUMBERS_6,  // ku-Latn-SY
    &NUMBERS_6,  // ku-TR
    &NUMBERS_0,  // kw
    &NUMBERS_11, // kxv
    &NUMBERS_11, // kxv-Deva
    &NUMBERS_11, // kxv-Latn
    &NUMBERS_11, // kxv-Orya
    &NUMBERS_11, // kxv-Telu
    &NUMBERS_1,  // ky
    &NUMBERS_0,  // la
    &NUMBERS_0,  // lag
    &NUMBERS_6,  // lb
    &NUMBERS_0,  // lg
    &NUMBERS_6,  // lij
    &NUMBERS_0,  // lkt
    &NUMBERS_6,  // lld
    &NUMBERS_24, // lmo
    &NUMBERS_6,  // ln
    &NUMBERS_6,  // ln-AO
    &NUMBERS_6,  // ln-CF
    &NUMBERS_6,  // ln-CG
    &NUMBERS_6,  // lo
    &NUMBERS_7,  // lrc
    &NUMBERS_7,  // lrc-IQ
    &NUMBERS_23, // lt
    &NUMBERS_0,  // ltg
    &NUMBERS_6,  // lu
    &NUMBERS_0,  // luo
    &NUMBERS_0,  // luy
    &NUMBERS_9,  // lv
    &NUMBERS_0,  // lzz
    &NUMBERS_0,  // mai
    &NUMBERS_0,  // mas
    &NUMBERS_0,  // mas-TZ
    &NUMBERS_0,  // mdf
    &NUMBERS_0,  // mer
    &NUMBERS_8,  // mfe
    &NUMBERS_0,  // mg
    &NUMBERS_6,  // mgh
    &NUMBERS_0,  // mgo
    &NUMBERS_0,  // mhn
    &NUMBERS_0,  // mi
    &NUMBERS_0,  // mic
    &NUMBERS_6,  // mk
    &NUMBERS_11, // ml
    &NUMBERS_0,  // mn
    &NUMBERS_0,  // mn-Mong
    &NUMBERS_0,  // mn-Mong-MN
    &NUMBERS_28, // mni
    &NUMBERS_28, // mni-Beng
    &NUMBERS_29, // mni-Mtei
    &NUMBERS_0,  // moh
    &NUMBERS_30, // mr
    &NUMBERS_0,  // ms
    &NUMBERS_0,  // ms-Arab
    &NUMBERS_6,  // ms-Arab-BN
    &NUMBERS_6,  // ms-BN
    &NUMBERS_6,  // ms-ID
    &NUMBERS_0,  // ms-SG
    &NUMBERS_0,  // mt
    &NUMBERS_6,  // mua
    &NUMBERS_0,  // mus
    &NUMBERS_26, // mww
    &NUMBERS_26, // mww-Hmnp
    &NUMBERS_31, // my
    &NUMBERS_0,  // myv
    &NUMBERS_7,  // mzn
    &NUMBERS_0,  // naq
    &NUMBERS_23, // nb
    &NUMBERS_23, // nb-SJ
    &NUMBERS_0,  // nd
    &NUMBERS_6,  // nds
    &NUMBERS_6,  // nds-NL
    &NUMBERS_30, // ne
    &NUMBERS_30, // ne-IN
    &NUMBERS_6,  // nl
    &NUMBERS_6,  // nl-AW
    &NUMBERS_6,  // nl-BE
    &NUMBERS_6,  // nl-BQ
    &NUMBERS_6,  // nl-CW
    &NUMBERS_6,  // nl-SR
    &NUMBERS_6,  // nl-SX
    &NUMBERS_1,  // nmg
    &NUMBERS_23, // nn
    &NUMBERS_6,  // nnh
    &NUMBERS_23, // no
    &NUMBERS_32, // nqo
    &NUMBERS_1,  // nr
    &NUMBERS_0,  // nso
    &NUMBERS_0,  // nus
    &NUMBERS_0,  // nv
    &NUMBERS_0,  // ny
    &NUMBERS_0,  // nyn
    &NUMBERS_1,  // oc
    &NUMBERS_1,  // oc-ES
    &NUMBERS_0,  // oka
    &NUMBERS_0,  // oka-US
    &NUMBERS_0,  // om
    &NUMBERS_0,  // om-KE
    &NUMBERS_11, // or
    &NUMBERS_1,  // os
    &NUMBERS_1,  // os-RU
    &NUMBERS_0,  // osa
    &NUMBERS_11, // pa
    &NUMBERS_7,  // pa-Arab
    &NUMBERS_11, // pa-Guru
    &NUMBERS_0,  // pap
    &NUMBERS_0,  // pap-AW
    &NUMBERS_0,  // pcm
    &NUMBERS_0,  // pi
    &NUMBERS_0,  // pi-Latn
    &NUMBERS_0,  // pis
    &NUMBERS_9,  // pl
    &NUMBERS_6,  // pms
    &NUMBERS_1,  // prg
    &NUMBERS_7,  // ps
    &NUMBERS_7,  // ps-PK
    &NUMBERS_6,  // pt
    &NUMBERS_1,  // pt-AO
    &NUMBERS_9,  // pt-CH
    &NUMBERS_9,  // pt-CV
    &NUMBERS_9,  // pt-GQ
    &NUMBERS_9,  // pt-GW
    &NUMBERS_9,  // pt-LU
    &NUMBERS_9,  // pt-MO
    &NUMBERS_9,  // pt-MZ
    &NUMBERS_9,  // pt-PT
    &NUMBERS_9,  // pt-ST
    &NUMBERS_9,  // pt-TL
    &NUMBERS_0,  // qu
    &NUMBERS_6,  // qu-BO
    &NUMBERS_0,  // qu-EC
    &NUMBERS_0,  // quc
    &NUMBERS_10, // raj
    &NUMBERS_0,  // rhg
    &NUMBERS_0,  // rhg-Rohg
    &NUMBERS_0,  // rhg-Rohg-BD
    &NUMBERS_0,  // rif
    &NUMBERS_17, // rm
    &NUMBERS_6,  // rn
    &NUMBERS_6,  // ro
    &NUMBERS_6,  // ro-MD
    &NUMBERS_0,  // rof
    &NUMBERS_1,  // ru
    &NUMBERS_1,  // ru-BY
    &NUMBERS_1,  // ru-KG
    &NUMBERS_1,  // ru-KZ
    &NUMBERS_1,  // ru-MD
    &NUMBERS_9,  // ru-UA
    &NUMBERS_6,  // rw
    &NUMBERS_0,  // rwk
    &NUMBERS_30, // sa
    &NUMBERS_1,  // sah
    &NUMBERS_0,  // saq
    &NUMBERS_33, // sat
    &NUMBERS_10, // sat-Deva
    &NUMBERS_33, // sat-Olck
    &NUMBERS_0,  // sbp
    &NUMBERS_6,  // sc
    &NUMBERS_6,  // scn
    &NUMBERS_34, // sd
    &NUMBERS_34, // sd-Arab
    &NUMBERS_0,  // sd-Deva
    &NUMBERS_3,  // sdh
    &NUMBERS_3,  // sdh-IQ
    &NUMBERS_23, // se
    &NUMBERS_23, // se-FI
    &NUMBERS_23, // se-SE
    &NUMBERS_6,  // seh
    &NUMBERS_8,  // ses
    &NUMBERS_6,  // sg
    &NUMBERS_0,  // sgs
    &NUMBERS_1,  // shi
    &NUMBERS_1,  // shi-Latn
    &NUMBERS_1,  // shi-Tfng
    &NUMBERS_0,  // shn
    &NUMBERS_0,  // shn-TH
    &NUMBERS_0,  // si
    &NUMBERS_0,  // sid
    &NUMBERS_1,  // sk
    &NUMBERS_0,  // skr
    &NUMBERS_35, // sl
    &NUMBERS_0,  // sma
    &NUMBERS_0,  // sma-NO
    &NUMBERS_0,  // smj
    &NUMBERS_0,  // smj-NO
    &NUMBERS_1,  // smn
    &NUMBERS_0,  // sms
    &NUMBERS_0,  // sn
    &NUMBERS_0,  // so
    &NUMBERS_0,  // so-DJ
    &NUMBERS_0,  // so-ET
    &NUMBERS_0,  // so-KE
    &NUMBERS_9,  // sq
    &NUMBERS_9,  // sq-MK
    &NUMBERS_9,  // sq-XK
    &NUMBERS_6,  // sr
    &NUMBERS_6,  // sr-Cyrl
    &NUMBERS_6,  // sr-Cyrl-BA
    &NUMBERS_6,  // sr-Cyrl-ME
    &NUMBERS_6,  // sr-Cyrl-XK
    &NUMBERS_6,  // sr-Latn
    &NUMBERS_6,  // sr-Latn-BA
    &NUMBERS_6,  // sr-Latn-ME
    &NUMBERS_6,  // sr-Latn-XK
    &NUMBERS_1,  // ss
    &NUMBERS_1,  // ss-SZ
    &NUMBERS_0,  // ssy
    &NUMBERS_0,  // st
    &NUMBERS_0,  // st-LS
    &NUMBERS_6,  // su
    &NUMBERS_6,  // su-Latn
    &NUMBERS_0,  // suz
    &NUMBERS_0,  // suz-Deva
    &NUMBERS_0,  // suz-Sunu
    &NUMBERS_23, // sv
    &NUMBERS_23, // sv-AX
    &NUMBERS_23, // sv-FI
    &NUMBERS_0,  // sw
    &NUMBERS_6,  // sw-CD
    &NUMBERS_0,  // sw-KE
    &NUMBERS_0,  // sw-UG
    &NUMBERS_0,  // syr
    &NUMBERS_0,  // syr-SY
    &NUMBERS_1,  // szl
    &NUMBERS_11, // ta
    &NUMBERS_11, // ta-LK
    &NUMBERS_0,  // ta-MY
    &NUMBERS_0,  // ta-SG
    &NUMBERS_11, // te
    &NUMBERS_0,  // teo
    &NUMBERS_0,  // teo-KE
    &NUMBERS_1,  // tg
    &NUMBERS_0,  // th
    &NUMBERS_0,  // ti
    &NUMBERS_0,  // ti-ER
    &NUMBERS_0,  // tig
    &NUMBERS_1,  // tk
    &NUMBERS_14, // tn
    &NUMBERS_14, // tn-BW
    &NUMBERS_0,  // to
    &NUMBERS_36, // tok
    &NUMBERS_0,  // tpi
    &NUMBERS_6,  // tr
    &NUMBERS_6,  // tr-CY
    &NUMBERS_0,  // trv
    &NUMBERS_0,  // trw
    &NUMBERS_1,  // ts
    &NUMBERS_1,  // tt
    &NUMBERS_8,  // twq
    &NUMBERS_8,  // tyv
    &NUMBERS_1,  // tzm
    &NUMBERS_0,  // ug
    &NUMBERS_1,  // uk
    &NUMBERS_0,  // und
    &NUMBERS_2,  // ur
    &NUMBERS_7,  // ur-IN
    &NUMBERS_1,  // uz
    &NUMBERS_7,  // uz-Arab
    &NUMBERS_1,  // uz-Cyrl
    &NUMBERS_1,  // uz-Latn
    &NUMBERS_0,  // vai
    &NUMBERS_0,  // vai-Latn
    &NUMBERS_0,  // vai-Vaii
    &NUMBERS_1,  // ve
    &NUMBERS_17, // vec
    &NUMBERS_6,  // vi
    &NUMBERS_6,  // vmw
    &NUMBERS_0,  // vo
    &NUMBERS_0,  // vun
    &NUMBERS_0,  // wa
    &NUMBERS_24, // wae
    &NUMBERS_0,  // wal
    &NUMBERS_0,  // wbp
    &NUMBERS_6,  // wo
    &NUMBERS_8,  // xh
    &NUMBERS_11, // xnr
    &NUMBERS_0,  // xog
    &NUMBERS_1,  // yav
    &NUMBERS_0,  // yi
    &NUMBERS_0,  // yo
    &NUMBERS_0,  // yo-BJ
    &NUMBERS_6,  // yrl
    &NUMBERS_6,  // yrl-CO
    &NUMBERS_6,  // yrl-VE
    &NUMBERS_0,  // yue
    &NUMBERS_0,  // yue-Hans
    &NUMBERS_0,  // yue-Hant
    &NUMBERS_0,  // yue-Hant-CN
    &NUMBERS_0,  // yue-Hant-MO
    &NUMBERS_0,  // za
    &NUMBERS_1,  // zgh
    &NUMBERS_0,  // zh
    &NUMBERS_0,  // zh-Hans
    &NUMBERS_0,  // zh-Hans-HK
    &NUMBERS_0,  // zh-Hans-MO
    &NUMBERS_0,  // zh-Hans-MY
    &NUMBERS_0,  // zh-Hans-SG
    &NUMBERS_0,  // zh-Hant
    &NUMBERS_0,  // zh-Hant-HK
    &NUMBERS_0,  // zh-Hant-MO
    &NUMBERS_0,  // zh-Hant-MY
    &NUMBERS_0,  // zh-Latn
    &NUMBERS_0,  // zu
];
